### ISSUE TITLE
Cross compiling with Open Watcom from any host to x86?

### ISSUE THREAD

**Issue by joncampbell123** [open-watcom/open-watcom-v2#176] opened 2015-06-07 07:49 UTC
I have a feature request that I'd like to help with implementing.

As far as I know, Open Watcom needs an x86 (32-bit or 64-bit) host to compile because it compiles itself, right? Is it possible to modify Open Watcom to instead bootstrap itself in a way that the compiler can run on non-x86 architectures and still generate working DOS & Windows executables? For example, if I were to compile Open Watcom to run on a Raspberry Pi (ARMv7 CPU) and then use it to make DOS programs for a nearby 486 or Pentium class PC?

If this capability already exists please let me know how to do it. I don't expect Open Watcom to generate code for non-x86 platforms so much but you could open up the compiler to a wider audience if you no longer had to use an x86 or x86_64 host to use it.

**Comment by jmalak** [comment] 2015-06-07 15:28
It is possible, but now ARM architecture is not supported.
What is necessary to do to be able build OW on Raspberry Pi even if OW is not able build for ARM?
1. must add appropriate macros to wmake to be able handle Raspberry Pi in make files.
2. must define new build_os and build_cpu macros.
3. extend makeinit build/makefile for Raspberry Pi
4. extend build/mif/local.mif makefile for Raspberry Pi compiler
5. modify/create build/clean batch scripts for Raspberry Pi
If Raspberry Pi is using some common Operating system you can extend existing makefile only for ARM architecture.
If you give me more details about Raspberry Pi OS and compiler I can help you with this much more.

**Comment by ArmstrongJ** [comment] 2015-06-07 15:38
I tried this a while back when I first received a Raspberry Pi, but I didn't pursue it.  The Raspberry Pi is almost certainly running a variety of GNU/Linux.  Most people are using Raspbian, a Debian derivative (almost identical to Debian, except the binary packages support the RPi's hardware FPU).  The system's compiler is GCC.  My RPi is running GCC 4.6 if I'm not mistaken.

I think adding support would actually be a great feature because the RPi is relatively popular with people running emulators, including DOSBox.  

If @joncampbell123 is asking for a port to RiscOS, though... that'd be significantly more difficult.  I'm guessing he's looking for Linux on ARM support as a host.

**Comment by jmalak** [comment] 2015-06-07 15:47
If I understand @joncampbell123 correctly then he is asking for OW running on RPi not for generation code for RPi.

**Comment by ArmstrongJ** [comment] 2015-06-07 15:54
@jmalak yes, I think that's what he's asking.  It should be rather straightforward to add support, especially given the list you've provided.  I can have a look since I believe my RPi actually already has this git repo on it.

Personally, I can see the appeal of being able to use OW to compile DOS executables on the RPi for use with DOSBox.

**Comment by jmalak** [comment] 2015-06-07 16:02
I think it could be a few days of effort to get it to work.
For me it is hard to test it because I have no RPi hardware.

**Comment by jmalak** [comment] 2015-06-08 20:40
I added wmake macro \_\_LINUXARM\_\_ to identify ARM on Linux by 6e01a06abcee27bf17f355baf2a13d1acaa2bf3b it can be used for RPi

**Comment by joncampbell123** [comment] 2015-07-23 11:42
I'm back..

I'm getting a compile error midway through:

========= 11:39:12 /usr/src/open-watcom-v2/bld/plusplus/386/binbuild ==========
cc carve.obj
In file included from ../../h/carvecpp.h:40:0,
                 from <command-line>:0:
../../h/pcheader.h:112:2: error: #error missing host architecture check
Error(E42): Last command making (carve.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
builder bootstrap build error
root@raspberry51:/usr/src/open-watcom-v2# 

Looking at bld/plusplus/h/pcheader.h I see don't see defines for ARM.

**Comment by ArmstrongJ** [comment] 2015-07-23 12:24
Commit 572b3e2 fixes this issue (as well as one further down the build process).  I've been building on RPi, and I'm at doc-build steps now, which is great.  I thought I'd push these changes before @jmalak needs to look at the problem.

**Comment by jmalak** [comment] 2015-07-23 13:20
I did comment to this commit.
It is necessary to decide what OW macro we will use for ARM.
From existing logic it should be __ARM__, target for -bt option should be arm.
Therefore we should add -D__ARM__ for native compiler and use __ARM__ macro for any code specific to ARM architecture.

**Comment by ArmstrongJ** [comment] 2015-07-23 13:40
Using `__ARM__` isn't probably not going to be sufficient.  We might want to decide on a better macro.  Here's a quick rundown:

* `__ARMEL__` refers to a little-endian (hence the "EL") 32-bit ARM architectures conforming to the ARM EABI in contrast to, for example, `__ARMEB__`, the big-endian alternative.  This terminology is used extensively by Debian GNU/Linux and its derivatives and the *BSD projects.  It usually indicates the platform, as opposed to the more generic term ARM.

* `__ARM__` refers to *all* ARM chips, including 64-bit ARM chips and all the various architectures and calling conventions.  The `__ARM__` macro probably would be far too generic.

* `__aarch64__` refers to ARM 64-bit chips, a whole other problem.

There are then further narrowing down with `__ARM_ARCH_*` values that further complicate matters since ARM architectures are always evolving.

I would prefer to stick with `__ARMEL__`, but I guess `__ARM__` could work too.  My only problem is that `__ARM__` is quite generic.

Again, though, I didn't think we were even considering ARM-specific code at this time.  I guess it makes sense to get some rules in place in case someone eventually wants to add ARM as a target.

**Comment by joncampbell123** [comment] 2015-07-23 14:15
Raspian seems to set GCC 4.6 as default, which doesn't recognize -std=c++11. So you'll want to document that GCC 4.8 should be installed, and made default, to compile Open Watcom from source.

**Comment by jmalak** [comment] 2015-07-23 17:46
To endianees in OW.
OW tools use separate option to control it. Therefore only one macro as __ARM__ is sufficient.
For endianees control __BIG_ENDIAN__ macro is defined or undefined.

To C++ standard. 
We need rework C++ code to be compilable by lower version of standard and do it more portable. It will be fine if somebody with appropriate C++ knowledge do this work.

**Comment by joncampbell123** [comment] 2015-07-23 18:47
It compiled all the way through, thanks! Now I will test to see if my Pi can build DOSLIB and DOSLIB2.

**Comment by joncampbell123** [comment] 2015-07-23 18:58
It's interesting that on the Pi, bwcc, etc. works from build/bin but the ELF binaries generated in rel/binl are still x86 ELF even on the Pi. DOSLIB looks for "wcc" in that directory for the compiler. Would it be possible for "builder rel" on the Pi to just copy the bootstrap compiler into rel/binl instead of generating x86 ELF versions there?

**Comment by jmalak** [comment] 2015-07-23 22:22
No you must do regular build to get real tools, because bootstrap tools have some specific reference.
By example bwlink uses bwlink.lnk configuration file and call bwlib and bwrc tools.
Real wlink uses wlink.lnk configuration file and call wlib and wrc tools.

**Comment by pchapin** [comment] 2015-07-26 16:01
@jmalak said:

"We need rework OW tools C++ code to be compilable by lower version of standard and do it more portable. It will be fine if somebody with appropriate C++ knowledge do this work."

I could possibly work on this, but I'm not clear about the issues. I don't see any other discussion of C++ in this thread (maybe I missed it?).

**Comment by joncampbell123** [comment] 2015-07-26 17:32
Unless the codebase is using the very latest C++ features, you could use -std=c++0x which GCC 4.6 does recognize and it would be perfectly fine. -std=c++0x was GCC's way at the time of enabling those C++ language features before it became C++11.

**Comment by pchapin** [comment] 2015-07-26 17:38
Open Watcom C++ is rather behind the standard so anything that it allows that GCC 4.6 does not in its default mode is probably an anomaly in Open Watcom... or at least a non-portability. Such a construction should probably be removed from the code base in the name of cleaning the code base up. I guess this is what Jiri is talking about.

**Comment by joncampbell123** [comment] 2015-07-26 17:41
Straying behind the C++ standard is fine. I have no intention of using C++ lamda functions and multithreading STL template objects in MS-DOS anyway. :)

**Comment by jmalak** [comment] 2015-07-26 18:04
I mean this is problem for OW tools which are using C++ source. Not for C++ compiler or C++ run-time library.
I am trying to use -std=c++98 option instead of -std=c++11 to work with older version gcc and clang compilers, by example this problem is on freeBSD and Haiku OS.

**Comment by pchapin** [comment] 2015-07-26 20:31
So the problem is manifest when doing a bootstrap build with gcc? I'll have to try and reproduce it so I can see what's going on. Do you happen to know which project(s) is/are involved? I'm going to guess Open Watcom is permitting something that should be illegal according to the modern standard.

**Comment by jmalak** [comment] 2015-07-26 20:38
I checked it now with gcc version 4.7.2 20130108 and -std=c++98 all is compiled except wipfc where is used <stdint.h> which was introduced by c++11.

**Comment by pchapin** [comment] 2015-07-27 11:49
It's a little distracting to talk about C++11 in this context. The header <stdint.h> is part of C99 and Open Watcom C++ can use it because it can just dip into the C headers that are available. We've implemented <stdint.h> as part of our C99 support. However, you are correct that it's not standard C++98. I'll look into fixing wipfc to make it more portable, but I don't currently have access to FreeBSD and Haiku.

**Comment by pchapin** [comment] 2015-07-27 11:59
I just took a quick look at wipfc. It appears that on Unix-like systems it assumes it will be configured with the autoconf tools... or that it can be configured in that way. Do the platforms where wipfc is a problem have &lt;stdint.h&gt;? My reading of the code is that, without configuration, it will try to use &lt;cstdint&gt; which is much less likely to exist.

So in short, the solution might be to just run the provided `configure` script before doing the build.

**Comment by jmalak** [comment] 2015-07-27 12:43
Thanks for review it and suggestion.
I will try to modify build make files for wipfc to use configure script on NIX like systems.

**Comment by jmalak** [comment] 2015-07-27 17:07
run configure script works OK.
Bellow is boot.log entries from freeBSD for clang compiler with some errors, not reported by g++.
Please, could you look on this?

================== 18:24:52 /root/owv2bsd/bld/hcwin/binbuild ==================
clang++ -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -Wno-self-assign -Wno-implicit-exception-spec-mismatch -ferror-limit=200 -O -g -o scanning.obj -std=c++11 -DNDEBUG -DBOOTSTRAP -D_M_IX86 -D__386__ -D__BSD_386__ -D__BSD__ -D__UNIX__ -D__FLAT__      -I"../h"  -I"/root/owv2bsd/bld/watcom/h" ../cpp/scanning.cpp
../cpp/scanning.cpp:91:16: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<uint_8>' and 'int')
        _buffer[0] = _buffer[_curPos];
        ~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:91:16: note: built-in candidate operator[](unsigned char *, int)
        _buffer[0] = _buffer[_curPos];
               ^
../cpp/scanning.cpp:91:16: note: built-in candidate operator[](const unsigned char *, int)
../cpp/scanning.cpp:91:16: note: built-in candidate operator[](volatile unsigned char *, int)
../cpp/scanning.cpp:91:16: note: built-in candidate operator[](const volatile unsigned char *, int)
../cpp/scanning.cpp:91:29: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<uint_8>' and 'int')
        _buffer[0] = _buffer[_curPos];
                     ~~~~~~~^~~~~~~~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:91:29: note: built-in candidate operator[](unsigned char *, int)
        _buffer[0] = _buffer[_curPos];
                            ^
../cpp/scanning.cpp:91:29: note: built-in candidate operator[](const unsigned char *, int)
../cpp/scanning.cpp:91:29: note: built-in candidate operator[](volatile unsigned char *, int)
../cpp/scanning.cpp:91:29: note: built-in candidate operator[](const volatile unsigned char *, int)
../cpp/scanning.cpp:95:20: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<uint_8>' and 'int')
    return( _buffer[_curPos++] );
            ~~~~~~~^~~~~~~~~~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:95:20: note: built-in candidate operator[](unsigned char *, int)
    return( _buffer[_curPos++] );
                   ^
../cpp/scanning.cpp:95:20: note: built-in candidate operator[](const unsigned char *, int)
../cpp/scanning.cpp:95:20: note: built-in candidate operator[](volatile unsigned char *, int)
../cpp/scanning.cpp:95:20: note: built-in candidate operator[](const volatile unsigned char *, int)
../cpp/scanning.cpp:104:16: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<uint_8>' and 'int')
        _buffer[--_curPos] = static_cast<uint_8>(c);
        ~~~~~~~^~~~~~~~~~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:104:16: note: built-in candidate operator[](unsigned char *, int)
        _buffer[--_curPos] = static_cast<uint_8>(c);
               ^
../cpp/scanning.cpp:104:16: note: built-in candidate operator[](const unsigned char *, int)
../cpp/scanning.cpp:104:16: note: built-in candidate operator[](volatile unsigned char *, int)
../cpp/scanning.cpp:104:16: note: built-in candidate operator[](const volatile unsigned char *, int)
../cpp/scanning.cpp:210:15: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
    tok->_text[0] = static_cast<char>(nextch());
    ~~~~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:210:15: note: built-in candidate operator[](char *, int)
    tok->_text[0] = static_cast<char>(nextch());
              ^
../cpp/scanning.cpp:210:15: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:210:15: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:210:15: note: built-in candidate operator[](const volatile char *, int)
../cpp/scanning.cpp:216:19: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
        tok->_text[i] = static_cast<char>(current);
        ~~~~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:216:19: note: built-in candidate operator[](char *, int)
        tok->_text[i] = static_cast<char>(current);
                  ^
../cpp/scanning.cpp:216:19: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:216:19: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:216:19: note: built-in candidate operator[](const volatile char *, int)
../cpp/scanning.cpp:218:15: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
    tok->_text[i] = '\0';
    ~~~~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:218:15: note: built-in candidate operator[](char *, int)
    tok->_text[i] = '\0';
              ^
../cpp/scanning.cpp:218:15: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:218:15: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:218:15: note: built-in candidate operator[](const volatile char *, int)
../cpp/scanning.cpp:246:15: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
    tok->_text[0] = static_cast<char>(nextch());
    ~~~~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:246:15: note: built-in candidate operator[](char *, int)
    tok->_text[0] = static_cast<char>(nextch());
              ^
../cpp/scanning.cpp:246:15: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:246:15: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:246:15: note: built-in candidate operator[](const volatile char *, int)
../cpp/scanning.cpp:262:45: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<uint_8>' and 'int')
            if( _curPos < _maxBuf && _buffer[_curPos] == '~' ) {
                                     ~~~~~~~^~~~~~~~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:262:45: note: built-in candidate operator[](unsigned char *, int)
            if( _curPos < _maxBuf && _buffer[_curPos] == '~' ) {
                                            ^
../cpp/scanning.cpp:262:45: note: built-in candidate operator[](const unsigned char *, int)
../cpp/scanning.cpp:262:45: note: built-in candidate operator[](volatile unsigned char *, int)
../cpp/scanning.cpp:262:45: note: built-in candidate operator[](const volatile unsigned char *, int)
../cpp/scanning.cpp:274:19: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
        tok->_text[i++] = static_cast<char>(current);
        ~~~~~~~~~~^~~~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:274:19: note: built-in candidate operator[](char *, int)
        tok->_text[i++] = static_cast<char>(current);
                  ^
../cpp/scanning.cpp:274:19: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:274:19: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:274:19: note: built-in candidate operator[](const volatile char *, int)
../cpp/scanning.cpp:276:15: error: use of overloaded operator '[]' is ambiguous (with operand types 'Buffer<char>' and 'int')
    tok->_text[i] = '\0';
    ~~~~~~~~~~^~
../h/hcmem.h:116:8: note: candidate function
    T &operator[]( size_t index ) { return _data[index]; };
       ^
../cpp/scanning.cpp:276:15: note: built-in candidate operator[](char *, int)
    tok->_text[i] = '\0';
              ^
../cpp/scanning.cpp:276:15: note: built-in candidate operator[](const char *, int)
../cpp/scanning.cpp:276:15: note: built-in candidate operator[](volatile char *, int)
../cpp/scanning.cpp:276:15: note: built-in candidate operator[](const volatile char *, int)
11 errors generated.
Error(E42): Last command making (scanning.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
====================== 18:24:52 /root/owv2bsd/bld/hcwin =======================

================= 18:26:57 /root/owv2bsd/bld/wclass/binbuild ==================
clang++ -pipe -c -fno-asm -fno-common -fsigned-char -Wall -Wno-switch -Wno-missing-braces -Wno-parentheses -Wno-self-assign -Wno-implicit-exception-spec-mismatch -ferror-limit=200 -O -g -o wfilenam.obj -std=c++11 -DNDEBUG -DBOOTSTRAP -D_M_IX86 -D__386__ -D__BSD_386__ -D__BSD__ -D__UNIX__ -D__FLAT__       -I"/root/owv2bsd/bld/wclass/hpp" -I"/root/owv2bsd/bld/gui/h"  -I"/root/owv2bsd/bld/watcom/h" /root/owv2bsd/bld/wclass/cpp/wfilenam.cpp
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:515:33: error: use of overloaded operator '[]' is ambiguous (with operand types 'const WFileName' and 'int')
        if( len > 0 && ( (*this)[0] != ch || (*this)[len - 1] != ch ) ) {
                         ~~~~~~~^~
/root/owv2bsd/bld/wclass/hpp/wstring.hpp:63:21: note: candidate function
        const char& operator[]( size_t index ) const { return( _value[index] ); }
                    ^
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:515:33: note: built-in candidate operator[](const char *, int)
        if( len > 0 && ( (*this)[0] != ch || (*this)[len - 1] != ch ) ) {
                                ^
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:515:33: note: built-in candidate operator[](const volatile char *, int)
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:528:16: error: use of overloaded operator '[]' is ambiguous (with operand types 'WFileName' and 'int')
    if( (*this)[0] == ch && (*this)[len] == ch ) {
        ~~~~~~~^~
/root/owv2bsd/bld/wclass/hpp/wstring.hpp:63:21: note: candidate function
        const char& operator[]( size_t index ) const { return( _value[index] ); }
                    ^
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:528:16: note: built-in candidate operator[](const char *, int)
    if( (*this)[0] == ch && (*this)[len] == ch ) {
               ^
/root/owv2bsd/bld/wclass/cpp/wfilenam.cpp:528:16: note: built-in candidate operator[](const volatile char *, int)
2 errors generated.
Error(E42): Last command making (wfilenam.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
====================== 18:26:57 /root/owv2bsd/bld/wclass ======================

**Comment by pchapin** [comment] 2015-07-27 19:02
Try converting the index value explicitly to size_t. The problem is the compiler finds two ways to interpret `buffer[0]`. It could either be the use of `operator[]` after converting the integer 0 to type size_t or the result of applying [] to the pointer returned after converting buffer to unsigned char *. Clang is right: this is ambiguous. Doing something like `buffer[static_cast<size_t>(0)]` should take care of it.

It is hugely ugly, of course. The right answer is to not include an implicit type conversion from buffer to unsigned char *, in class Buffer (line 115 of hcmem.h), but making that change will probably require more fixes in the long run (maybe try it first and see how bad it is?). In some cases, changing types to size_t elsewhere would probably also be appropriate but that will likely cause a significant ripple effect as well.

The program was written without much attention to types and this is what you get as a result.

**Comment by jmalak** [comment] 2015-07-27 19:16
Thanks for analysis.
I understand that there are quick solution and right solution. 
Probably I will change  type for array index to size_t, even if it will require more work.
I think it will simplify porting.

**Comment by jmalak** [comment] 2015-07-29 06:24
It looks like I fixed all errors.
Now it compiles on freeBSD.
Please can anybody confirm if it is still problem on ARM Rapsbery Pi.

**Comment by ytrezq** [comment] 2015-08-03 19:22
@pchapin cross compiling from windows 32 bits alpha should work. #183

**Comment by ArmstrongJ** [comment] 2015-08-08 22:17
@jmalak Looks like the ARM on RPi is failing building **wasm**:
```
======= 18:15:38 /home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm ========
gcc -pipe  -O -g -o wasm.exe  -Wl,-Map,wasm.map main.obj write.obj fatal.obj womputil.obj direct.obj posndir.obj asmeval.obj asmalloc.obj asmmsg.obj wasmmsg.obj macro.obj condasm.obj breakout.obj asmstruc.obj asmexpnd.obj mangle.obj for.obj objio.obj carve.obj genmsomf.obj objrec.obj queue.obj fixup.obj lifix.obj asmins.obj asmscan.obj asmline.obj asmsym.obj tbyte.obj asmlabel.obj asmfixup.obj asmmatch.obj asmdata.obj asmjump.obj autodept.obj queues.obj pathlist.obj   /home/jeff/Workspace/open-watcom-v2/bld/watcom/binbuild/clibext.lib
wasmmsg.obj: In function `res_seek':
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:168: undefined reference to `FileShift'
wasmmsg.obj: In function `MsgFini':
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:201: undefined reference to `CloseResFile'
wasmmsg.obj: In function `MsgGet':
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:232: undefined reference to `WResLoadString'
wasmmsg.obj: In function `MsgInit':
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:181: undefined reference to `OpenResFile'
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:182: undefined reference to `FindResources'
/home/jeff/Workspace/open-watcom-v2/bld/wasm/linuxarm/../c/wasmmsg.c:182: undefined reference to `InitResources'
collect2: error: ld returned 1 exit status
Error(E42): Last command making (wasm.exe) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 512
Build failed
```

**Comment by jmalak** [comment] 2015-08-09 07:14
wres.lib definition was missing for arm target.
It is fixed by 88ba38150611a07f6ea48a29d6c0404484a38372 in git repository.

**Comment by jmalak** [comment] 2015-08-09 18:21
I looked a little bit on compilers predefined macros for ARM architecture.
Now we have it inconsistent in local.mif 
We should use macro compatible with Microsoft that it should be \_M\_ARM macro, similar as \_M\_PPC, \_M\_ALPHA macros.
I am sorry that I did some confution by introduction \_\_ARM\_\_ macro, but it could be second predefined macro for arm architecture similar as \_\_PPC\_\_ and \_\_AXP\_\_ macros.

**Comment by ArmstrongJ** [comment] 2015-08-09 18:25
@jmalak whichever macro you think is best.  `__arm__` will work with most every GNU-ish compiler.  I like the MS compatibility, however.

It appears that my ARM build is progressing nicely at this point.

**Comment by jmalak** [comment] 2015-08-09 18:50
I doesn't mather what other compilers use, because in local.mif is defined OW macros for each compilers which are used in OW source code. What non-Watcom compilers uses is OK for compiler header files etc.

**Comment by ArmstrongJ** [comment] 2015-08-13 19:41
@jmalak Open Watcom finished building and completed a `builder rel` successfully on my Raspberry Pi (I ran into some DOSBox issues separate from OW while trying to finish the build).  Everything appears to be in order if you want to close this "bug."

**Comment by jmalak** [comment] 2015-08-14 04:34
Good News. You should check if all OW tools are build. May be some of them is missing. If something is not in arml release subdirectory than linuxarm subdirectory must be add to appropriate project and appropriate copy command to builder.ctl. Unfortunately installer for Raspberrry Pi could be created, now not configured.

**Closed** 2016-01-13 09:41 UTC
