### ISSUE TITLE
build fails when using ow 1.9

### ISSUE THREAD

**Issue by ideafarm** [open-watcom/open-watcom-v2#163] opened 2015-04-21 01:46 UTC
Build fails when 1.9 is installed from: open-watcom-c-win32-1.9.exe (from ftp://ftp.openwatcom.org/).

Build works aok when 1.9 has been uninstalled and 2.0 is installed from: open-watcom-2_0-c-win-x64.exe dated 2015-04-02 100.4 MB (from http://sourceforge.net/projects/openwatcom/files/current-build/).

Details:  Windows Server 2012 R2 (Rackspace virtual server).

I am reporting this FYI so that Jiri can ensure that he doesn't find himself without a snapshot of binaries that can be used to build OW20.  IOW, OW2.0 can only be built with itself; which is a dangerous thing, if true, since it is being actively developed.

**Comment by jmalak** [comment] 2015-04-21 17:26
more info is needed, what exactly fails and on which platform.
Fragment with failure from build log also help.

**Comment by ideafarm** [comment] 2015-04-21 19:10
Of course.  This "issue" is just FYI so that you might save a snapshot of the current binaries, which work.  I didn't provide details because I intend to find this bug myself in the next month or two, after I become familiar with the code as I debug the debugger.  (I'm working on that right now!)

**Comment by ArmstrongJ** [comment] 2015-04-21 19:14
I build nightly with OW 1.9 binaries on Debian Linux, and I'm not seeing any problems building.

@ideafarm if you're going to report a bug, you need to provide some details.  This bug report is basically useless as-is.  I would suggest closing the bug unless someone can reproduce the issue.

**Comment by rdos314** [comment] 2015-04-21 19:56
I think we know that RDOS won't build with 1.9 because they have still not fixed the compiler bug in the 1.9 release AFAIK. They actually can't because by fixing the bug they no longer can build with 1.9. Other than that, there shouldn't be any issues. That's also why you cannot build RDOS device-drivers with 1.9 as this will generate faulty code.

**Comment by jmalak** [comment] 2015-04-21 20:55
I am using 1.9 version for build on Windows 32/64-bit and Linux 32/64-bit and no problem with it.
If you have any trouble it signal some OW environment configuration problem.

**Comment by ideafarm** [comment] 2015-04-22 00:08
If you leave this issue open, I will eventually get around to working on it.  The build definitely fails when building a virgin clone of the current repository using 1.9 but not when using 2.0.

**Comment by jmalak** [comment] 2015-04-22 00:32
You have something wrong. OW 2.0 is compilable by both OW1.9 and OW2.0.

**Comment by ideafarm** [comment] 2015-05-16 18:24
I've fixed some problems with my build environment and intend to attempt to reproduce this problem within the next 30 days.

**Closed** 2017-11-02 07:31 UTC
