### ISSUE TITLE
Linux Installer: Program received signal SIGFPE, Arithmetic Exception

### ISSUE THREAD

**Issue by giulianobelinassi** [open-watcom/open-watcom-v2#225] opened 2016-01-21 17:28 UTC
I'm trying to install the OpenWatcom-v2 lastest build on Linux Debian 8 with kernel 3.16.0-4-686-pae, but the installer is receiving a Floating Point Exeption.
Running the installer with GDB provides me the following output:

Program received signal SIGFPE, Arithmetic exception.
0x0805c89d in GUIGetRoundScale_ ()

Altrough I found something about creating a link:
sudo ln -s /lib/terminfo/x /usr/share/terminfo
that does not seems to work. I also tried copying the /lib/terminfo/x to  /usr/share/terminfo manually.

**Comment by jmalak** [comment] 2016-01-22 18:19
Thanks for bug report.
Are you using pure terminal  or xterminal?
What type of terminal you are using?
What is content of TERM environment variable.

Thanks

**Comment by wyatt8740** [comment] 2016-01-26 04:23
I've had this problem in 64 bit debian in an xterminal. TERM variable = xterm.
The program is mate-terminal.

I have a real hardware IBM 3161 terminal if it'd change anything to try building it on that.

**Comment by wyatt8740** [comment] 2016-01-26 04:41
Yeah, confirmed. Works on the real terminal. (TERM variable = ibm3161)

http://i.imgur.com/UIQ33qG.jpg

**Comment by giulianobelinassi** [comment] 2016-01-26 18:35
I'm using the default gnome3 terminal. I also tried using xterm and CTRL-ALT-F1, but none of those works..

Content of the TERM variable:

giuliano@Lazarus:~/Downloads$ echo $TERM
xterm

**Comment by jmalak** [comment] 2016-01-26 20:21
Many Thanks for your info and your effort to get more details.
Nice picture of old serial link terminal.
It looks like problem with detecting xterm type of terminal and therefore size of terminal is set to zero (0x0) and next in code is division by zero. 
@seyko2 prepared some fixes for this in pull request https://github.com/open-watcom/open-watcom-v2/pull/205
I will review it and apply to fix this old problem.

**Comment by wyatt8740** [comment] 2016-01-27 01:10
Glad to hear it. The installer worked really well with it; I was impressed.

Some popular programs didn't work with this very well - nano would redraw the entire screen for each character typed with syntax highlighting on, and manpages hardcode VT100 escape sequences. The installer was very well-behaved (though not on xterm).

**Comment by wyatt8740** [comment] 2016-01-27 14:36
Also, if anyone is having trouble and doesn't have a serial link terminal, maybe setting the TERM variable to 'vt100' will work?

**Comment by jmalak** [comment] 2018-02-19 12:00
It should be fixed by 9465e4a8aad7d46ed7cf3a4ec7fa57c0cb203715 submit.
Now default list of path for searching terminfo database is changed to
"/usr/local/ncurses/share/terminfo:/usr/share/terminfo:/lib/terminfo"
old list contained only
"/usr/share/terminfo"
I hope it fixes similar problem with unknown terminals for all OW tools for Linux/UNIX.

**Closed** 2018-03-13 08:36 UTC
Labels: bug
