### ISSUE TITLE
E1119: Internal compiler error 67

### ISSUE THREAD

**Issue by youshitsune** [open-watcom/open-watcom-v2#1056] opened 2023-03-17 16:46 UTC
I get this error when try to compile my project using **make** command.

**Comment by youshitsune** [comment] 2023-03-17 16:50
`#include "disk.h"
#include "x86.h"
#include "stdio.h"

bool DISK_Initialize(DISK* disk, uint8_t driveNumber){
    
    uint8_t driveType;
    uint16_t cylinders, sectors, heads;

    if (!x86_Disk_GetDriveParams(disk->id, &driveType, &cylinders, &sectors, &heads)){
        return false;
    }

    disk->id = driveNumber;
    disk->cylinders = cylinders + 1;
    disk->heads = heads + 1;
    disk->sectors = sectors;

    return true;
}

void DISK_LBA2CHS(DISK* disk, uint32_t lba, uint16_t* cylinderOut, uint16_t* sectorOut, uint16_t* headOut){
    *sectorOut = lba % disk->sectors + 1;
    *cylinderOut = (lba / disk->sectors) / disk->heads;
    *headOut = (lba / disk->sectors) % disk->heads;
}

bool DISK_ReadSectors(DISK* disk, uint32_t lba, uint8_t sectors, void far* dataOut){
    uint16_t cylinder, sector, head;
    DISK_LBA2CHS(disk, lba, &cylinder, &sector, &head);
    
    for (int i = 0; i < 3; i++){
        if(x86_Disk_Read(disk->id, cylinder, sector, head, sectors, dataOut))
            return true;
        x86_Disk_Reset(disk->id);
    }

    return false;
}

`
I get: **disk.c(41): Error! E1119: Internal compiler error 67**
But disk.c only has 40 lines.

**Comment by jmalak** [comment] 2023-03-18 00:54
The problem happen during compilation when is no relation between source code and processing.
Therefore is reported line after last line.
Anyway it reports internal error that I need fully compilable code to be able analyze what is reason for this message.

**Comment by youshitsune** [comment] 2023-03-18 06:12
I pushed my code with error to my repo: https://github.com/youshitsune/os

**Comment by jmalak** [comment] 2023-03-18 19:58
Thanks for your test code.
But I am not able reproduce it. Below is make output.

```
jiri@jiri-VirtualBox:~/os$ make
mkdir -p build
make -C src/bootloader/stage1 BUILD_DIR=/home/jiri/os/build
make[1]: Entering directory '/home/jiri/os/src/bootloader/stage1'
nasm boot.asm -f bin -o /home/jiri/os/build/stage1.bin
make[1]: Leaving directory '/home/jiri/os/src/bootloader/stage1'
make -C src/bootloader/stage2 BUILD_DIR=/home/jiri/os/build
make[1]: Entering directory '/home/jiri/os/src/bootloader/stage2'
mkdir -p /home/jiri/os/build/stage2/c
mkdir -p /home/jiri/os/build/stage2/asm
nasm -f obj -o /home/jiri/os/build/stage2/asm/main.obj main.asm
nasm -f obj -o /home/jiri/os/build/stage2/asm/x86.obj x86.asm
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/ctype.obj ctype.c
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/disk.obj disk.c
disk.c(10): Warning! W102: Parameter 5: Type mismatch (warning)
disk.c(10): Note! N2003: source conversion type is 'unsigned short *'
disk.c(10): Note! N2004: target conversion type is 'unsigned short'
disk.c(10): Note! N2002: 'x86_Disk_GetDriveParams' defined in: x86.h(8)
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/fat.obj fat.c
fat.c(66): Warning! W131: No prototype found for function 'DISK_ReadSector'
fat.c(66): Warning! W308: The function 'DISK_ReadSector' without prototyped parameters called
fat.c(66): Note! N2002: 'DISK_ReadSector' defined in: fat.c(66)
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/main.obj main.c
main.c(40): Warning! W102: Parameter 1: Type mismatch (warning)
main.c(40): Note! N2003: source conversion type is 'char *'
main.c(40): Note! N2004: target conversion type is 'char'
main.c(40): Note! N2002: 'putc' defined in: stdio.h(4)
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/memory.obj memory.c
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/stdio.obj stdio.c
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/string.obj string.c
~/ow20/binl/wcc -4 -d3 -s -wx -ms -zl -zq -za99  -fo=/home/jiri/os/build/stage2/c/utility.obj utility.c
utility.c(8): Error! E1009: Expecting ';' but found 'return'
utility.c(9): Warning! W138: No newline at end of file
make[1]: *** [Makefile:23: /home/jiri/os/build/stage2/c/utility.obj] Error 1
make[1]: Leaving directory '/home/jiri/os/src/bootloader/stage2'
make: *** [Makefile:42: build/stage2.bin] Error 2
jiri@jiri-VirtualBox:~/os$ 
```

there is a few errors, but I don't get "Compiler Internal Error"

How you have configured OW?
From make files it is not clear because you use absolute reference to OW tools.
It is not standard and it can case many problems with mixing header files etc.

**Comment by youshitsune** [comment] 2023-03-19 07:54
I installed full installation, I didn't configured anything after that.

**Comment by jmalak** [comment] 2023-03-19 08:25
You don't need to install full OW if you need only some target or host system.

OW is designed to not need any specific installation or to be install by sudo.
You can have multiple versions or multiple installation of same version on host.
You simply create configuration script for each of your version and run it before use.

But if I understand correctly your OW use then you use only compilers and linker without OW run-time environment.
Best configuration in this case is to change
CC16=/usr/bin/watcom/binl/wcc
LD16=/usr/bin/watcom/binl/wlink
to
CC16=wcc
LD16=wlink
then you can simply change PATH by script to appropriate location and it will be working without need to change any make file.
It also ensure that all OW tools will be available because some OW tools call other OW tools, by example owcc tool call compilers and linker and assemblers etc.
You need not to configure anything other for your use.
You can place OW anywhere, only user need to access it for read/execute
for you is enough to copy only OW binl or binl64 to your box somewhere, no other OW folders.
If you do full installation nothing wrong only you will install lot of files which you doesn't need.

OW tools are working with your make files as is, that no change is needed.
But configure it by PATH is safe.

**Comment by youshitsune** [comment] 2023-03-19 09:36
I have changed it, but it throws same error again.

**Comment by jmalak** [comment] 2023-03-19 09:53
My note is only about how you use OW, but doesn't fix issue.
I have a problem that I cannot reproduce it on your git repository.
Please what command you use to demonstarate this issue, because if I run make it doesn't fail as you describe.

**Comment by youshitsune** [comment] 2023-03-19 09:55
I just run **make** from root of repo

**Comment by jmalak** [comment] 2023-03-19 10:04
It is strange. I got different result then you that it is somehow related to your environment.
Do you compiled OW or you use download from Github?

**Comment by youshitsune** [comment] 2023-03-19 10:05
I installed it from GitHub

**Comment by youshitsune** [comment] 2023-03-19 10:06
Before, I got same error and than added flags which i use now.

**Comment by jmalak** [comment] 2023-03-19 10:23
It could be a problem with some inconsistent things, because it is error reported if something wrong happen during Code Generation.
Please, are you able to create some new test repository which reproduce it?
May be it is not useful now if it is working.

**Comment by jmalak** [comment] 2023-03-20 08:52
Thanks, it compile without error.
I am sorry, but Internal compiler error 67 dodn't happen.
Please could you give me output from env command.
What Linux version you are using?

**Comment by jmalak** [comment] 2023-03-20 15:52
Thanks.
I don't see anything strange.
I will try to install Arch Linux on VM and check if I can reproduce.
What version you have 32-bit or 64-bit?

**Comment by jmalak** [comment] 2023-03-20 21:16
I install Arch Linux 6.2.7 and download latest OW and test it.
I am sorry but it works without any exception.

**Comment by youshitsune** [comment] 2023-03-21 05:58
I have fixed it.

First, I uninstalled OW, then reinstalled it without using sudo.
After, I didn't get **Internal compiler error**.

**Comment by jmalak** [comment] 2023-03-21 06:15
Thanks for your info.
It looks like OW installer don't setup some file permission correctly.
I will hold this issue open as bug to be fixed in the future.

**Comment by jmalak** [comment] 2023-03-22 10:13
I checked rights for installed file and all looks OK.
The files are readable for any user and executable files have executable flag defined.
I checkd to install OW by sudo and all is also OK.
I tried install OW under sudo and compile os project under regular user and it compiles also without exception.
I close it for now.

**Closed by jmalak** 2023-03-22 10:13 UTC
Labels: bug, installer
