### ISSUE TITLE
Relative path bug

### ISSUE THREAD

**Issue by HnkGitHub** [open-watcom/open-watcom-v2#668] opened 2021-03-04 01:05 UTC
Git v. O30221
Platform: Server 2003 -32 bit
Built with watcom 1.9

Ide fails to process relative paths. Have to check absolute paths check box for the target to build. Building a project in a folder two folders separated from root. Source folder's located next to root.

This was working about 3 months ago. Appears the program's attempting to rebuild the absolute path name but is leaving out the '\\'. Before the drive letter.

**Comment by jmalak** [comment] 2021-03-04 06:38
Thanks for bug report.
I am not sure if I understand your issue.
Please could you give me example.

**Comment by jmalak** [comment] 2021-03-05 11:08
I tried to check with latest version of OW and can not reproduce similar problem.
Please I need more detailed description.
I tested it on 32-bit version of Windows-XP without problem.

**Comment by HnkGitHub** [comment] 2021-03-10 03:28
Ok. I have the source code in a folder called e:\hello. I open a new watcom project in folder e:\watcom\hello hello.wpj is in this second folder. It's empty except for the project name. I'm expecting the output object files, exe, etc. To be placed here by the ide. Attached a picture to illustrate what's happening. This same project will build no problems in 1.9.
![hello](https://user-images.githubusercontent.com/38794884/110572073-56c9cd80-811e-11eb-8a8c-3f30fc8a741e.png)

**Comment by jmalak** [comment] 2021-03-10 07:16
Thanks for problem example.
It looks like error in drive processing when full path is created for compiler.
I will fix it.

**Comment by jmalak** [comment] 2021-03-13 15:34
It should be fixed now. You can use last CI build to replace existing installation or use current Build installers after rebuild.

**Closed** 2021-03-23 18:05 UTC
Labels: bug
