### ISSUE TITLE
`#pragma once` does not work if files referenced by alternate paths

### ISSUE THREAD

**Issue by mmastrac** [open-watcom/open-watcom-v2#714] opened 2021-06-29 16:20 UTC
Repro attached.

`test.c`:
```
#include "base.h"
#include "x/inc.h"
```

`base.h`:
```
#pragma once
struct foo {
        int bar;
};
```

`x/inc.h`
```
#pragma once
#include "../base.h"
```

Using `2021-05-01` build.

Expected result: successful compile (works in gcc/llvm)
Actual result: `/home/x/../base.h(3): Error! E1019: Tag 'foo' already defined`
Workaround: `#ifdef` guards 

[repro.zip](https://github.com/open-watcom/open-watcom-v2/files/6734927/repro.zip)

**Comment by jmalak** [comment] 2021-06-29 17:15
Thanks for bug report.
I confirm this bug in both C and C++ compilers.

**Comment by jmalak** [comment] 2021-08-12 12:14
It is standard OW behaviour for any version to use specified name(in source file) instead of OS fullpath.
I will change behaviour to use OS fullpath for comparision then it should work as expected.
The problem is common for similar pragmas which works with path or file name that they must be fixed too.

**Comment by jmalak** [comment] 2021-08-14 07:06
Now it should be fixed in git repository.

**Closed** 2021-09-12 06:59 UTC
Labels: bug
