### ISSUE TITLE
C code optimization

### ISSUE THREAD

**Issue by beketata** [open-watcom/open-watcom-v2#210] opened 2015-11-14 18:57 UTC
I am using wcc.exe as a C compiler to generate code for 80186 embedded system.
Used options for wcc are the next:
-1 -ohs -zl -ml -s -zu -zdp -bt=rawbin

Here is an example of a fictional C code:
```
// External Data located in the segRAM segment which is not equal to DS
//
extern word __far16 _w1;
extern word __far16 _w2;
extern word __far16 _w3;
extern word __far16 _w4;

void fn()
{
  _w1 = 0;
  _w2 = 0;
  _w3 = 0;
  _w4 = 0;
}
```
wcc generates the next instructions from the C code above:
```
mov     ax, seg segRAM
mov     es, ax
xor     ax, ax
mov     es:_w1, ax

mov     ax, seg segRAM
mov     es, ax
xor     ax, ax
mov     es:_w2, ax

mov     ax, seg segRAM
mov     es, ax
xor     ax, ax
mov     es:_w3, ax

mov     ax, seg segRAM
mov     es, ax
xor     ax, ax
mov     es:_w4, ax
```

What is the way to optimize it to something like the next?
```
mov     ax, seg segRAM
mov     es, ax
xor     ax, ax
mov     es:_w1, ax
mov     es:_w2, ax
mov     es:_w3, ax
mov     es:_w4, ax
```

**Comment by jmalak** [comment] 2015-11-14 20:17
Bellow is proper code where you define in which segment is variable located (uses __based ).

```
short __based(__segname("RAM")) w1;
extern short __based(__segname("RAM")) w2;
extern short __based(__segname("RAM")) w3;
extern short __based(__segname("RAM")) w4;

void fn1( void )
{
  w1 = 0;
  w2 = 0;
  w3 = 0;
  w4 = 0;
}
```

Disassembled code compiled with your options is

```
                PUBLIC  fn1_
                PUBLIC  _w1
                EXTRN   _w2:BYTE
                EXTRN   _w3:BYTE
                EXTRN   _w4:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
t1_TEXT         SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:t1_TEXT, DS:DGROUP, SS:DGROUP
fn1_:
        mov             ax,seg _w1
        mov             es,ax
        xor             ax,ax
        mov             word ptr es:_w1,ax
        mov             word ptr es:_w2,ax
        mov             word ptr es:_w3,ax
        mov             word ptr es:_w4,ax
        retf
t1_TEXT         ENDS
CONST           SEGMENT WORD PUBLIC USE16 'DATA'
CONST           ENDS
CONST2          SEGMENT WORD PUBLIC USE16 'DATA'
CONST2          ENDS
_DATA           SEGMENT WORD PUBLIC USE16 'DATA'
_DATA           ENDS
RAM             SEGMENT WORD PUBLIC USE16 ''
_w1:
    DB  0, 0

RAM             ENDS
                END
```

**Comment by beketata** [comment] 2015-11-14 21:16
Thank you.
My project contains a few **C** and one **asm** file and variables _w1, _w2, _w3, _w4 are defined in the **asm** file under **segRAM** data segment. Thus, for the relative to **C** file (where I want to use them) they are external and I coud not define them twice with __based directive.

**Comment by jmalak** [comment] 2015-11-14 22:00
You only declare (not define) "asm" variables in C as extern (by example w2 variable)
extern short __based(__segname("segRAM")) w2;
Then C know segment where variables are defined

**Comment by jmalak** [comment] 2015-11-14 22:05
Bellow is example with declaration only. C code
```
extern short __based(__segname("RAM")) w2;
extern short __based(__segname("RAM")) w3;
extern short __based(__segname("RAM")) w4;

void fn1( void )
{
  w2 = 0;
  w3 = 0;
  w4 = 0;
}
```
Disassembled code
```
                PUBLIC  fn1_
                EXTRN   _w2:BYTE
                EXTRN   _w3:BYTE
                EXTRN   _w4:BYTE
                EXTRN   _small_code_:BYTE
DGROUP          GROUP   CONST,CONST2,_DATA
_TEXT           SEGMENT BYTE PUBLIC USE16 'CODE'
                ASSUME CS:_TEXT, DS:DGROUP, SS:DGROUP
fn1_:
        mov             ax,seg _w2
        mov             es,ax
        xor             ax,ax
        mov             word ptr es:_w2,ax
        mov             word ptr es:_w3,ax
        mov             word ptr es:_w4,ax
        ret
_TEXT           ENDS
CONST           SEGMENT WORD PUBLIC USE16 'DATA'
CONST           ENDS
CONST2          SEGMENT WORD PUBLIC USE16 'DATA'
CONST2          ENDS
_DATA           SEGMENT WORD PUBLIC USE16 'DATA'
_DATA           ENDS
RAM             SEGMENT WORD PUBLIC USE16 ''
RAM             ENDS
                END
```

**Comment by beketata** [comment] 2015-11-15 06:22
Thank you for your prompt answer.

Unfortunately, it does not work for me with the next linker error:
**Error! E2120: application too large to run under DOS**.

You could download the sample from http://akitel.com/Test_Based.zip

**Comment by jmalak** [comment] 2015-11-15 06:29
Could you create map file and add it here.
Do you use remaping/location of segments?
Please, add here full wlink command.

**Comment by jmalak** [comment] 2015-11-15 06:45
Sorry, I overlook your link.
It is problem with wlink, because executable is declared as DOS but is embeded OS.
Therefore your executable is checked for DOS memory limits by wlink.
In wlink were added in the past support for segment location and for raw and binary output.
But these stuff is not logical from wlink point of view (internal processing) and have similar side efect.
It will require to rework this stuff to have some targets as "real mode" and "protected mode" which define extra target for wlink to not apply any OS checking etc.
Also raw and binary should be output formats not target etc.

Anyway I will look for some workaround until it will be fixed by changing wlink functionality.

**Comment by beketata** [comment] 2015-11-15 07:14
Sure, the executable is checked for DOS memory (1 Mb) limits by wlink.
But in this case is something wrong with segments allocation and their names/classes.
When I replaced **__based( __segname( "RAM1" ) )** with **__far16** everything linked fine.
But with the **__based( __segname( "RAM1" ) )** the linker creates another segment with the same name **RAM1** and does not recognize the existing one. Thus, it is leads to oversize 1 Mb DOS limit.

**Comment by beketata** [comment] 2015-11-15 07:19
Anyway, the C compiler with **__far16** instead of **__based** knows about the segment base of all variables. What is the reason to say it explicity with **__based** ?

**Comment by beketata** [comment] 2015-11-15 08:17
I moved the variable definitions to **C** file with **#pragma data_seg** and made them as **EXTERN** in **asm** file. In this "enveronment" everything compiles as expected: http://akitel.com/Test_Based_1.zip

**Comment by jmalak** [comment] 2015-11-15 08:40
Your solution is probably best, shared variables defined in C and use it from asm.
Support for segments in C is very limited. The __based define segment as other data segment (public). Segment class definition must be done by #pragma data_seg( "RAM1", "RAM"). You can not define segment alignment and visibility it is fixed. All these attribute have impact to grouping segment. It is important that declaration of segment must be same in C and in ASM source.
Original problem was that __based segment have had no class therefore they was not in class "RAM" and they was locate after last segment  (over 1Mb boundary).

To be sure that both definition is OK you should do

in C code
#pragma data_seg( "RAM1", "RAM )

in ASM code
RAM1 segement public 'RAM'

After that variable can be defined either in C or in ASM and no problem.

**Comment by jmalak** [comment] 2015-11-15 08:46
anyway use of __far16 can be dangerous because it is same as __far for 16-bit but different for 32-bit.
But it is not your case.

**Comment by jmalak** [comment] 2015-11-15 08:59
__based enable compiler to do more optimization because compiler know exact segment where variable/function is that compiler can use only offset if it is possible or you can use based pointer (only offset).
But __far cannot be optimized any way because compiler not know what segment is used.

**Comment by beketata** [comment] 2015-11-15 09:01
Thank you once again.
But now I faced with another issue. When I defined those variables in **C**, the compiler does not keep their listed order and shuffles them in memory.
How could force compiler to keep the order of variables in which they are defined in file ?

**Comment by jmalak** [comment] 2015-11-15 09:06
Generaly C doesn't preserve variable order.
If you need exact order then you must define it in ASM code.

**Comment by jmalak** [comment] 2015-11-15 09:07
For sure give me wlink map file

**Comment by jmalak** [comment] 2015-11-15 09:35
One correction C segment use word alignment but in ASM uses implicit para alignment

to fix it you can define in ASM code
RAM1 segment word public 'RAM'

**Comment by beketata** [comment] 2015-11-15 16:31
Sorry, it's my mistake in the message about **#pragma data_seg**.
Moving the variable definitions to **C** file is does not helps. I looked at the other disassembled file after compiling.

Map file shows that the vars are laid at the proper segments:
```
1000:0000+     __w2
1000:0002+     __w3
1000:0004+     __w1
2000:0000+     __w6
2000:0002+     __w4
2000:0004+     __w5
```
But disassembled code of fn() with **#pragma data_seg( "RAM1", "RAM" )** is
```
xor     ax, ax
mov     ds:4, ax
mov     ds:0, ax
mov     ds:2, ax
mov     ds:2, ax
mov     ds:4, ax
mov     ds:0, ax
retf
```

**Comment by jmalak** [comment] 2015-11-15 21:10
This declaration/definition ensure that you get what you expect.
```
#pragma data_seg ( "RAM1", "RAM" );
#pragma data_seg ( "RAM2", "RAM" );

short __based( __segname( "RAM1" ) ) _w1;
short __based( __segname( "RAM1" ) ) _w2;
short __based( __segname( "RAM1" ) ) _w3;

short __based( __segname( "RAM2" ) ) _w4;
short __based( __segname( "RAM2" ) ) _w5;
short __based( __segname( "RAM2" ) ) _w6;
```

**Comment by jmalak** [comment] 2015-11-15 21:21
Another possibility is to define extra two C modules with far data segment and define variables there.
Only __based enable to refere more far segments in one module.
Standard C modules can use one near and one far data segment only.

**Comment by beketata** [comment] 2015-11-16 11:38
Could you be so kind to provide me with an example (as mine in Zip file).
Unfortunately, I could not find the proper way to build the simple project to get what I expect:
```
mov             ax,seg _w1
mov             es,ax
xor             ax,ax
mov             word ptr es:_w1,ax
mov             word ptr es:_w2,ax
mov             word ptr es:_w3,ax
```
Thank you in advance!

**Comment by jmalak** [comment] 2015-11-16 16:19
I enclosed changed file from your example (remove .txt extension). If you replace it you get compilable sample with definition variables in C code and use it from ASM code.

[build.bat.txt](https://github.com/open-watcom/open-watcom-v2/files/35700/build.bat.txt)
[main.asm.txt](https://github.com/open-watcom/open-watcom-v2/files/35701/main.asm.txt)
[test.c.txt](https://github.com/open-watcom/open-watcom-v2/files/35702/test.c.txt)

**Comment by beketata** [comment] 2015-11-16 17:50
I'm very sorry, but after building your files I've got the next result for fn():
```
xor     ax, ax
mov     ds:0, ax
mov     ds:2, ax
mov     ds:4, ax
mov     ds:4, ax
mov     ds:0, ax
mov     ds:2, ax
retf
```

**Comment by jmalak** [comment] 2015-11-16 19:36
The problem is with compiler segment definition.
I checked it with __based only without #pragma data_seg.
It created correct segment which is not in DGROUP that it generate proper code.
But if I use #pragma data_seg then it looks like compiler thing it is segment in DGROUP.
Probably some new #pragma will be necessary for add segment class to segment if it is not defined but it should not change type of segment. give me some time to thing about solution which doesn't break backward compatibility and will be useful for future.

**Comment by jmalak** [comment] 2015-11-16 21:42
I fixed C compiler now, C++ compiler is OK.
C compiler now define correct segment class 'FAR_DATA' for __based segments.
You can not change class for based segment but now it is correctly 'FAR_DATA' that you can define location in wlink.
Bellow is new version of files which properly compile with fixed C compiler.

[main.asm.txt](https://github.com/open-watcom/open-watcom-v2/files/36005/main.asm.txt)
[test.c.txt](https://github.com/open-watcom/open-watcom-v2/files/36006/test.c.txt)
[Test.lnk.txt](https://github.com/open-watcom/open-watcom-v2/files/36007/Test.lnk.txt)

**Comment by beketata** [comment] 2015-11-17 11:35
Thank you very much for your help.

I downloaded the latest version of sources with fixed **wcc** and when I try to build them I've got the next error at the first phase **build.bat**:
```
========================= 17:32:46 c:\WATCOM\bld\trap =========================
============= 17:32:46 c:\WATCOM\bld\trap\lcl\dos\dosx\cw\dos.srv =============
============= 17:32:46 c:\WATCOM\bld\trap\lcl\dos\dosx\cw\dos.trp =============
%create cw.lnk
bwlink op q @cw.lnk
Error! E2030: file clibc.lib(cstart): multiple starting addresses found, already defined in dosstrt.obj(TRAPSTRT)
Error! E2028: main_ is an undefined reference
file clibc.lib(cmain086.c): undefined symbol main_
Error(E42): Last command making (cw.trp;w) returned a bad status
Error(E02): Make execution terminated
<pmake -d build         -h> => non-zero return: 2
Build failed
```

**Comment by jmalak** [comment] 2015-11-18 06:37
it should be fixed now, the problem was with using mkstemp function in trap file that it requires big portion of CRTL. I replaced it by hand coded processing which doesn't use CRTL because trap files don't have standard startup code.

**Comment by beketata** [comment] 2015-11-18 08:18
Thank you!
Now it's compiles as expected with 'FAR_DATA'.

**Comment by jmalak** [comment] 2015-11-18 08:50
Thanks for confirmation. Thanks your problem I fixed one problem in near data segments handling introduced by OW developer in the past. It was attempt  to create near data segment which is outside DGROUP group, but it is not simply possible because code generator is not able properly handle near segment outside DGROUP group it always assume all near segment are in DGROUP. Only FAR data segments can be outside DGROUP group.

**Closed by jmalak** 2015-11-18 08:50 UTC
