### ISSUE TITLE
Executables in `BINW` folder get linked with DOS/4GW in DOS version, making them non-Free

### ISSUE THREAD

**Issue by volkertb** [open-watcom/open-watcom-v2#917] opened 2022-07-03 14:47 UTC
I just downloaded https://github.com/open-watcom/open-watcom-v2/releases/download/2022-07-01-Build/open-watcom-2_0-c-dos.exe and then ran the installer with the "-s" option (non-interactive) in a freshly installed FreeDOS 1.3 VM running under QEMU.

After the (by the way remarkably slow) installation process, I ran `C:\WATCOM\OWSETENV.BAT`, after which I ran a few tools from the command-line as a sanity check (`wcc`, `wlink`, etc). To my surprise, the first lines these tools displayed on the console were these:

```
DOS/4GW Protected Mode Run-time  Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
```

I know DOS/4GW (the variant with the `W` at the end) is free-as-in-beer, but to my knowledge, it's still a closed-source component, or at least one of which the distribution of the source code is restricted. This makes the DOS builds of Open Watcom v2 on the releases page currently non-Free (as in speech).

If there were no alternatives, than that could have been an argument to still depend on DOS/4GW. But with both DOS/32A and CauseWay being available as fully compatible open-source drop-in replacements, why aren't the executables in the DOS version of Open Watcom v2 being built with either of those DOS extenders instead?

**Comment by jmalak** [comment] 2022-07-03 21:35
I can try to explain my opinion about it.
DOS4GW extender Version 1.97 and 2.01 is free for use with Open Watcom, it was confirmed by Copyright owner that it can be distributed with Open Watcom. Therefore no reason to change it.
The change to another extenders is possible but not simple, because other extenders are not same as DOS4GW on low level.
By example OW sampler is released with regards appropriate Watcom support in DOS4GW extender.
DOS version of Debugger is also based on DOS4GW API. Generaly each DOS Extender has own internal API etc.
Anyway such change requires some effort for no gain, that I don't have any plan to change it.
If anybody is interested in such change (I prefer to use Causeway extender which is part of OW) then it can be done as contribution to OW2.

**Comment by volkertb** [comment] 2022-07-03 23:28
> The change to another extenders is possible but not simple, because other extenders are not same as DOS4GW on low level.
> By example OW sampler is released with regards appropriate Watcom support in DOS4GW extender.
> DOS version of Debugger is also based on DOS4GW API. Generaly each DOS Extender has own internal API etc.

Thanks for the explanation, and for pointing out that macro.

I'm not sure how well the state of actual compatibility is in the case of CauseWay, but [DOS/32A was specifically designed to be a drop-in replacement for DOS/4GW](https://dos32a.narechk.net/index_en.html). A patching tool is available to replace DOS/4GW with DOS/32A in many protected mode games and applications. It sometimes even improves performance, and [with some exceptions, it works quite well](https://github.com/dosbox-staging/dosbox-staging/wiki/DOS-32A-compatibility-list).

Perhaps [this specific page in the DOS/32A manual](https://www.dos32a.narechk.net/manual/html/util/5.htm) is also useful, since it explains how "to force DOS/32 Advanced to emulate DOS/4GW DOS Extender as close as possible".

At what point would you feel comfortable trying to swap out DOS/4GW for CauseWay or DOS/32A? Would it be a matter of extending existing test coverage first?

**Comment by jmalak** [comment] 2022-07-04 06:42
> > The change to another extenders is possible but not simple, because other extenders are not same as DOS4GW on low level.
> > By example OW sampler is released with regards appropriate Watcom support in DOS4GW extender.
> > DOS version of Debugger is also based on DOS4GW API. Generaly each DOS Extender has own internal API etc.
> 
> Thanks for the explanation, and for pointing out that macro.
> 
> I'm not sure how well the state of actual compatibility is in the case of CauseWay, but [DOS/32A was specifically designed to be a drop-in replacement for DOS/4GW](https://dos32a.narechk.net/index_en.html). A patching tool is available to replace DOS/4GW with DOS/32A in many protected mode games and applications. It sometimes even improves performance, and [with some exceptions, it works quite well](https://github.com/dosbox-staging/dosbox-staging/wiki/DOS-32A-compatibility-list).
> 
> Perhaps [this specific page in the DOS/32A manual](https://www.dos32a.narechk.net/manual/html/util/5.htm) is also useful, since it explains how "to force DOS/32 Advanced to emulate DOS/4GW DOS Extender as close as possible".
> 
> At what point would you feel comfortable trying to swap out DOS/4GW for CauseWay or DOS/32A? Would it be a matter of extending existing test coverage first?

I don't think that DOS/32 is replacement on full functionality and internal API.
We can talk about Extended DOS API it can be equivalent (what functions are extended to 32-bit protected-mode and parameters), but we can not talk about internals, it is different world.
From application point of view such compatibility is enough, but sampler and debugger need access to internal API which are different. By example DOS4GW use 16-bit kernel and has loadable modules, one of them is 32-bit support.
Causeway on other hand has 32-bit kernel with 16-bit support etc. Most of OW tools can be simply re-link with other extender but sampler and debugger is different story.

**Comment by Baron-von-Riedesel** [comment] 2022-07-08 16:19
> Most of OW tools can be simply re-link with other extender but sampler and debugger is different story.

Hello,
as far as WD is concerned, this view is perhaps a bit too pessimistic.
I rebuilt OW v1.9 WD as HX PE binary, and it worked out of the box. I guess it's mainly because WD acts more or less as a frontend to the "real" debuggers, which are the trap (helper) files.

In case you want to verify, here's my little project: https://github.com/Baron-von-Riedesel/HX-OpenWatcom-Debugger

[Unlike the name suggests, the trap files are not restricted to the HX extender binaries, they should be able to generally debug DPMI applications]

**Comment by jmalak** [comment] 2022-07-11 17:51
I recompile OW DOS version with Causeway DOS Extender and enclose it here.
I am not using DOS that no testing is possible.
I checked to recompile OW2 by this version of OW on DOS system and it works.
[binw.zip](https://github.com/open-watcom/open-watcom-v2/files/9086434/binw.zip)

**Comment by Baron-von-Riedesel** [comment] 2022-07-12 04:02
> I am not using DOS that no testing is possible.

But why not run such things with DOS in a Qemu VM? I ask because the last OW 2.0 WD for DOS that I tested ( 30.6.2022 ) doesn't run at all, just freezes the machine. So to test it cannot be spared, IMO.

**Comment by Baron-von-Riedesel** [comment] 2022-07-12 04:46
> I recompile OW DOS version with Causeway DOS Extender and enclose it here.

I tried this WD version on real DOS with a simple DOS binary ( no debug info in binary, no /TR=x  argument ). It loads it and I can see the the startup code, but trying to single-step ( pressing F8 ) makes the machine freeze ( running that test with WD of OW v1.9 works smoothly ) .

**Comment by jmalak** [comment] 2022-07-12 06:39
I submit change d9364a82d1af4d02b9df67b8508727c84d916dfe
which switch DOS build to Causeway extender that all tools use now Causeway extender instead of DOS4GW
Debugger is still Work-in-progress that there is exception it uses DOS4GW

**Comment by volkertb** [comment] 2022-07-12 18:35
> > I am not using DOS that no testing is possible.
> 
> But why not run such things with DOS in a Qemu VM? I ask because the last OW 2.0 WD for DOS that I tested ( 30.6.2022 ) doesn't run at all, just freezes the machine. So to test it cannot be spared, IMO.

@jmalak I recently created [a Docker project](https://github.com/volkertb/cicd-qemu-dos-docker) that makes it possible to automatically run DOS commands under QEMU as part of a CI/CD pipeline. It works with GitHub Actions, and if you want, I can create a PR to integrate this in the GitHub workflow(s) of the `open-watcom-v2` project.

**Comment by jmalak** [comment] 2022-07-12 19:17
We already use Azure Pipelines no GitHub Action for OW build and test, because Azure Pipelines provides unlimited resources for open source projects. By example OW building use parallel 10 jobs about 2 hours to build complete OW for 64-bit Linux and Windows and OSX and 32-bit version for all supported platforms. Such resource are not available on Github Action.
We use dosbox for some documentation build tasks that we could use it for DOS related tasks.
For using OW we have following repository which simplify complete setup of OW for using in other projects [OW Setup](https://github.com/open-watcom/setup-watcom).

**Comment by Baron-von-Riedesel** [comment] 2022-07-13 05:41
Just for the record: the current OW2.0 16-bit Windows debuggers (WDW and WDC ) work in Win31 standard mode and also in DosEmu.

**Comment by jmalak** [comment] 2022-07-13 06:05
Thanks for your info.

**Closed** 2022-07-20 10:53 UTC
