### ISSUE TITLE
Inline assembly fmul instruction emitted as fmulp

### ISSUE THREAD

**Issue by negge** [open-watcom/open-watcom-v2#756] opened 2021-11-07 07:50 UTC
When writing inline assembly FPU code the `fmul` instruction is emitted as `fmulp`. Consider the example:

```c
static float test_fmul(float a, float b);
#pragma aux test_fmul parm [ 8087 ] [ 8087 ] = \
  "fmul" \
  "fstp st" \
  value [ 8087 ]

void main() {
  test_fmul(0, 1);
}
```

Compiling and disassembling gives:

```bash
$ wcc386 -q -s test2.c
$ wdis test2.o 
Module: test2.c
GROUP: 'DGROUP' CONST,CONST2,_DATA

Segment: _TEXT BYTE USE32 0000000B bytes
0000				main_:
0000  D9 E8				fld1
0002  D9 EE				fldz
0004  DE C9				fmulp		st(1),st
0006  DD D8				fstp		st
0008  DD D8				fstp		st
000A  C3				ret

Routine Size: 11 bytes,    Routine Base: _TEXT + 0000
```

This loads two FPU values, but then pops 3 off the stack. The `fmul` should not be an `fmulp`.

**Comment by jmalak** [comment] 2021-11-07 09:50
Same problem as #755  working only for FPU predefined constant only.
Try for variables and you get error.

**Comment by negge** [comment] 2021-11-07 10:36
Hi @jmalak, this is with the same compiler options as #755 `$ wcc386 -q -s test.c`.

**Comment by jmalak** [comment] 2021-11-08 19:21
Your code sample is now not compiled and report error in operands

```
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Nov  8 2021 18:26:41 (32-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
t2.c(5): Error! E1156: Assembler error: 'Invalid instruction operands'
t2.c: 24 lines, 0 warnings, 1 errors
```

It is due to FMUL must have operand.

following code sample with FMULP works

```
extern float t1( float a, float b );

extern float test_fmul( float a, float b );
#pragma aux test_fmul = \
  "fmulp" \
  parm [__8087] [__8087] value [__8087]

float t1( float a, float b )
{
    return( test_fmul( a, b ) );
}
```

is compiled as

```
t1_:
        push            eax
        fld             dword ptr [esp+0cH]
        fld             dword ptr [esp+8]
        fmulp           st(1),st
        pop             eax
        ret             8
```

**Comment by jmalak** [comment] 2021-11-08 19:23
it is now fixed in git repository

**Comment by jmalak** [comment] 2021-11-09 15:00
For backward compatibility I enable FMUL without operands again and it generates FMULP by default.
It is default behaviour for following FPU instructions without operands
| Used old | Used new | Generated |
| --- | --- | --- |
| FADD | FADDP | FADDP ST(1),ST(0) |
| FDIV | FDIVP | FDIVP ST(1),ST(0) |
| FDIVR | FDIVRP | FDIVRP ST(1),ST(0) |
| FMUL | FMULP | FMULP ST(1),ST(0) |
| FSUB | FSUBP | FSUBP ST(1),ST(0) |
| FSUBR | FSUBRP | FSUBRP ST(1),ST(0) |

**Comment by negge** [comment] 2021-11-11 01:54
I found similar behavior in nasm and filed a bug here: https://bugzilla.nasm.us/show_bug.cgi?id=3392787

**Comment by jmalak** [comment] 2021-11-11 06:09
It is not a bug, it was defined this way in the past and for backward compatibility with MASM and stay here for while.
I added only new mnemonics for this.
I also changed OW code base to use less confusing "pop" form with explicit operands to be clear.

**Closed** 2021-11-11 08:23 UTC
Labels: bug
