### ISSUE TITLE
An unnamed namespace can't be reopened in the same translation unit

### ISSUE THREAD

**Issue by Mazdaywik** [open-watcom/open-watcom-v2#277] opened 2016-08-28 08:17 UTC
If source file have a number of unnamed namespaces, Open Watcom compiler considers it as different namespaces, but other compilers (BCC 5.5, Visual C++ 18.00.40629, GCC (g++) 4.8.1, CLang 3.7.0) consider as one namespace. This code shows it:

``` C++
namespace {
  extern int x;
}

namespace {
  int x = 0;
}

int f() {
  return ++x;
}
```

```
Open Watcom C/C++ CL Clone for 386
Version 2.0 beta Apr  2 2015 11:27:33 (32-bit)
…copyrights skipped…
test-don’t-work.cpp
test-don’t-work.cpp(10): Error! E857: col(12) namespace lookup is ambiguous
test-don’t-work.cpp(10): Note! N858: col(12) ambiguous namespace symbol is 'x'
test-don’t-work.cpp(6): Note! N392: col(7) definition: 'int <unique>::x'
test-don’t-work.cpp(6): Note! N858: col(7) ambiguous namespace symbol is 'x'
test-don’t-work.cpp(2): Note! N392: col(14) definition: 'int <unique>::x'
```

Open Watcom can’t understand that `extern int x` in line 2 declare variable `x` that defined in line 6.

But, in this source with same sense is successfully compiled:

``` C++
namespace {
  extern int x;

  int x = 0;
}

int f() {
  return ++x;
}
```

Attachments:
- [test-don’t-work.cpp](https://github.com/open-watcom/open-watcom-v2/files/441040/test-don.t-work.cpp.txt)
- [test-don’t-work.err](https://github.com/open-watcom/open-watcom-v2/files/441042/test-don.t-work.err.txt)
- [test-work.cpp](https://github.com/open-watcom/open-watcom-v2/files/441041/test-work.cpp.txt)

**Comment by jmalak** [comment] 2016-08-28 18:23
Thanks for your bug report.
OW C++ compiler need to improve support for name spaces and templates.

**Comment by bmanga** [comment] 2017-03-24 13:29
Hi, it should work if you pass the -za (disable extensions) flag.
I am not sure why that doesn't work with extensions enabled, I am guessing for backward compatibility.

It would be interesting to discuss whether to change this behavior by default, or just hide all the compiler standardization efforts behind that flag.

**Comment by pchapin** [comment] 2017-03-25 02:31
I think it's a bug. Without checking the standard (because I'm lazy!), it is normally possible to reopen namespaces. The unnamed namespace is a little different in that it is private to the translation unit in which it appears, but I'm going to guess that it should still be possible to reopen it in that translation unit. The fact that it works that way with other compilers suggests reopening is correct.

I don't think this has anything to do with extensions. It should work regardless.

**Comment by jmalak** [comment] 2017-03-25 06:09
I think so it is bug and should be fixed.
Behaviour of unnamed namespace should be same as named namespace on this point (reopenning).
It can break some of C++ regression test that it must be fixed to follow fixed behaviour.

**Comment by bmanga** [comment] 2017-03-27 13:03
@jmalak this can be closed now.

**Closed** 2017-03-27 21:27 UTC
Labels: bug
