### ISSUE TITLE
Programs using LocalAlloc crash on Windows 9x.

### ISSUE THREAD

**Issue by ccawley2011** [open-watcom/open-watcom-v2#852] opened 2022-04-17 09:37 UTC
Example program:

```
#include <windows.h>
#include <tchar.h>

int WINAPI _tWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nShowCmd) {
	HLOCAL pCopy = LocalAlloc(LMEM_FIXED, 12);
	if (!pCopy) {
		return 0;
	}

	MessageBox(NULL, TEXT("Allocated successfully"), TEXT("Test"), MB_ICONHAND);

	LocalFree(pCopy);

	return 0;
}
```

When compiled with OpenWatcom using `wcl386 -q -fe=test-watcom.exe -bcl=nt_win -bt=nt test.c`, it works fine with Windows XP, but crashes on Windows 98 SE with the following error:

```
TEST-WATCOM caused an invalid page fault in
module KERNEL32.DLL at 0167:bff7b350.
Registers:
EAX=c00309c8 CS=0167 EIP=bff7b350 EFLGS=00090246
EBX=00000108 SS=016f ESP=0052fce4 EBP=0052fcf4
ECX=81919f44 DS=016f ESI=81919f44 FS=1c27
EDX=00000000 ES=016f EDI=00000000 GS=0eb6
Bytes at CS:EIP:
ff 72 4c e8 69 8f ff ff f7 c7 8d 80 ff ff 74 0c 
Stack dump:
00000000 81919f44 00000108 0052fce0 0052fe2c 00401025 00000000 0000000c 00000108 0040126d 00400000 00000000 005400bd 0000000a 00433000 00000000 
```

The same program compiled with MinGW using `gcc -o test-mingw.exe test.c -mwindows` works fine on both Windows XP and Windows 98.

**Comment by jmalak** [comment] 2022-04-17 11:05
I think you use wrong command for compilation.
Correct one is 
**`wcl386 -q -fe=test-watcom.exe -bt=nt -l=nt_win test.c`**
or
**`wcl386 -q -fe=test-watcom.exe -bt=nt -l=win95 test.c`**

**Comment by ccawley2011** [comment] 2022-04-17 18:51
That doesn't seem to have made a difference.

**Comment by ccawley2011** [comment] 2022-04-21 13:11
This seems to be a recent regression - using OpenWatcom from Nov 6 2021 seems to work fine, but OpenWatcom from Jan 17 2022 doesn't. I'll try bisecting to see if I can identify which commit caused this.

**Comment by ccawley2011** [comment] 2022-04-21 22:28
Looks like 1c06db8 is the first commit to exhibit this issue.

**Comment by jmalak** [comment] 2022-04-22 05:36
#853

**Comment by deltabeard** [comment] 2023-05-28 09:52
I am currently getting this issue with the build at https://github.com/open-watcom/open-watcom-v2/commit/d9ee9b8f5ee071f705088c170098f06f199f243e in Windows 95, whereby I'm using the 16-bit Windows Installer to install the 32-bit executables due to issue #853.

Launching the IDE (C:\WATCOM\Binnt\Ide.exe), I get the following error:
```
IDE caused an invalid page fault in
module KERNEL32.DLL at 0157:bff79981.
Registers:
EAX=c00181ac CS=0157 EIP=bff79981 EFLGS=00000206
EBX=00000024 SS=015f ESP=0059fc24 EBP=0059fc34
ECX=81590e1c DS=015f ESI=00000002 FS=256f
EDX=00000000 ES=015f EDI=00000042 GS=272e
Bytes at CS:EIP:
ff 72 4c e8 60 a8 ff ff f7 c7 8d 80 ff ff 74 0c 
Stack dump:
005b0c68 00000002 00000024 00000001 00000002 00442a55 00000042 00000024 00000080 00000080 00000002 10c800c0 00000080 005b0000 0000000a 0042ae00 
```

The same error appears for programs running on Windows 95 that were compiled using the 32-bit compiler on Windows 10.

Thanks.

**Comment by joncampbell123** [comment] 2023-12-28 07:45
Confirmed. The code compiled in DOSLIB for Windows 2.x through Win32 (Win95) and WinNT crashes under Windows 95. All 16-bit builds work fine in Windows 2.x through Windows 95. The Win32s binary works fine in Windows 3.1 Win32s subsystem.

I have Visual C++ 4.2 in a DOSBox-X VM set up to debug the crash:
![guest os_000](https://github.com/open-watcom/open-watcom-v2/assets/6245486/548aa30f-af95-4777-bee8-563024d11e53)

How exactly did someone manage to jump or call to 0x00000006?

Speaking of which, this is also proof of what I mean when I tell people that NULL pointers are 100% valid in Windows 95, because you can absolutely read, write, and even execute code from a NULL pointer.

**Comment by joncampbell123** [comment] 2023-12-28 07:46
The same code compiled with Visual C++ 4.2 runs fine in Windows 95.
![guest os_001](https://github.com/open-watcom/open-watcom-v2/assets/6245486/185283d0-b278-4235-b59e-89a9c5284383)

**Comment by joncampbell123** [comment] 2023-12-28 15:43
Maybe this isn't the cause, but why do Watcom compiled EXEs have a PE header that reports a OS version number of 1.11 (0x0001, 0x000B)?

This is from the windows/localalloc hello.c test program, Win32 build:

Windows NT EXE Header                             
==============================================================================
file offset = 00000080H

cpu type (32-bit)                               =     014CH
number of object entries                        =     0004H
time/date stamp                                 = 658D93E6H
symbol table                                    = 00000000H
number of symbols                               = 00000000H
no. of bytes in nt header following flags field =     00E0H
flags                                           =     0182H
magic (32-bit)                                  =     010BH
link major version number                       =       02H
link minor version number                       =       12H
code size                                       = 00004000H
initialized data size                           = 00000800H
uninititialized data size                       = 00000000H
entrypoint rva                                  = 00001046H
code base                                       = 00001000H
data base                                       = 00005000H
image base                                      = 00400000H
object alignment: power of 2, 512 to 256M       = 00001000H
file alignment factor to align image pages      = 00000200H
**os major version number                         =     0001H**
**os minor version number                         =     000BH**
user major version number                       =     0000H
user minor version number                       =     0000H
**subsystem major version number                  =     0004H**
**subsystem minor version number                  =     0000H**

**Comment by joncampbell123** [comment] 2023-12-28 15:53
Found the culprit:

Look at the stack and heap reserve fields, specifically "size of local heap to reserve"

This is from a DOSLIB binary where LocalAlloc crashes:

    stack reserve size                              = 00100000H
    stack commit size                               = 00010000H
    size of local heap to reserve                   = 00000000H
    heap commit size                                = 00001000H

If I hex edit the "size of local heap to reserve" field to 00100000H to match what Microsoft Visual C++ 4.2 does, the binary works properly.

    stack reserve size                              = 00100000H
    stack commit size                               = 00010000H
    size of local heap to reserve                   = 00100000H
    heap commit size                                = 00001000H

![guest os_002](https://github.com/open-watcom/open-watcom-v2/assets/6245486/a57ece2f-e3d5-45b2-87c7-46bea256b57c)

Fix that and you'll get LocalAlloc to work properly in Windows 95 again.

**Comment by jmalak** [comment] 2023-12-29 09:25
Many Thanks for your analysis and fix of the problem.
It looks like that older systems require some committed pages, cannot be zero.
I will fix OW linker to setup default value (non zero) for committed pages (if size not specified).
I think we don't need to do this rule somehow specific by OS version that simple rule will be applied for all OS versions.

**Comment by joncampbell123** [comment] 2024-01-03 23:54
Now that the PE header lists a non-zero commit size I think it's appropriate to close this issue since that is required for LocalAlloc() to work.

**Closed** 2024-01-04 11:10 UTC
Labels: bug, WLINK
