### ISSUE TITLE
OW Win16 build installs a "damaged" WDEBUG.386

### ISSUE THREAD

**Issue by pwroberts** [open-watcom/open-watcom-v2#1018] opened 2022-12-31 00:17 UTC
* Host platform: Win16 (Windows for Workgroups 3.11)
* OW build: 2022-12-30 [Current-build](https://github.com/open-watcom/open-watcom-v2/releases/tag/Current-build) (commit e29f83b4e82c2e8644f9b3df9594c577aa7410d9)

After installing OpenWatcom from open-watcom-2_0-c-win16.exe and restarting the machine, Windows complains (during startup) that WDEBUG.386 is "damaged" (see screenshot below). The OW IDE then (predictably) complains about WDEBUG not being loaded.

I encountered the error on a real 486 machine, but I reproduced it in a virtual machine to check it wasn't just old hardware being flaky.

The error is not observed with the oldest build available in Releases ([2020-09-08](https://github.com/open-watcom/open-watcom-v2/releases/tag/2020-09-08-Build)).

The 2020-09-08 and 2022-12-30 versions of WDEBUG.386 (labeled "good" and "bad" in the zip attached below) differ by just 5 bytes, and 2 of those are part of the version string at the end of the file.

![2022-12-30](https://user-images.githubusercontent.com/16436731/210118648-fc6ee8d4-7841-4496-a04b-c5b79c7a222e.png)
[wdebug.386_good_and_bad.zip](https://github.com/open-watcom/open-watcom-v2/files/10326566/wdebug.386_good_and_bad.zip)

**Comment by jmalak** [comment] 2022-12-31 07:38
Thanks for bug report.
It could be related to some changes in wlink which affected VXD target.

**Comment by pwroberts** [comment] 2022-12-31 20:52
Thanks Jiří. I did a little more bisecting of releases and confirmed that the WDEBUG.386 binary changed sometime this month (i.e. the 2022-12-01 release binary was still identical to the "good" version from 2020-09-08). So quite possibly due to https://github.com/open-watcom/open-watcom-v2/commit/c43fe485e2e64ee161417fb559bdd3d9460d9ce4 (changes wlink's VXD writing - the changes you were referring to, I guess) or https://github.com/open-watcom/open-watcom-v2/commit/f24e2969b49156ca9e9155f8668797340b046343#diff-51aef725ef24ff6dc6aef0ea3b3f4e0f4697ac8fb62b74f777597a0f1cacb8e3 (changes wdebug code, maybe a long shot though).

**Comment by jmalak** [comment] 2022-12-31 21:44
It looks like problem with first rather then second change, there are macros and symbol name changes only.

**Comment by jmalak** [comment] 2023-01-17 01:43
It is build break caused by mistake in Push request #1015
Now wlink is fixed to properly generate VxD executable in any case.
Please recheck with latest version of VxD driver (wdebug.386).
It is fixed by commit e334303027a43a3cb7079494e93822ab3a962fce
Please recheck new version of VxD driver

**Closed** 2023-01-25 20:15 UTC
Labels: bug
