### ISSUE TITLE
istream::getline broken

### ISSUE THREAD

**Issue by igorzhitko** [open-watcom/open-watcom-v2#240] opened 2016-03-04 20:11 UTC
I'm russian and have small practice in english. Sorry for mistakes.
I have a message file with numbers and strings in one project. Eg. " 15  16 Pulser error". Some string contains russian letter 'я' (0xFF in cp1251). Eg "  4  28 Показания уровнемера".
I read all lines by ifstream.getline. In OW 1.x and 2.0beta1 LA (from 07/07/11) all work is Ok. In new OW 2, I read only "  4  28 Показани". Read stops at 0xFF char.
I look through sources, found istgline.cpp with istream::getline and istgalin.cpp with __getaline. These functions have not changed since OW 1.
Could this be a bug in the code generator?

**Comment by jmalak** [comment] 2016-03-05 05:57
Thanks for bug reporting.
Even if source is not changed it is not well portable.
To improve portability( to fix problems ) I change compiler option for char type from unsigned to signed. It is root cause for your problem. I will fix it ASAP and note you when it will be fixed.

**Comment by jmalak** [comment] 2016-03-11 00:26
I did a review of ifstream class implementation and did a few changes 5becfb4c086e3b9f0b15aefa6e2fa8fa05eeaac8 and 3f25a81c818bec4536cee86fe0b7fb9f4c9de6ff.
Now class behaviour should be independent on compiler -j option.

**Closed** 2016-04-02 22:52 UTC
Labels: bug
