### ISSUE TITLE
The application has failed to start because its side-by-side configuration is incorrect.

### ISSUE THREAD

**Issue by omm** [open-watcom/open-watcom-v2#376] opened 2017-09-20 13:58 UTC
Hi!

Tested with Open Watcom Linker Version 2.0 beta Sep 19 2017 08:38:40 (32-bit)
Copyright (c) 2002-2017 The Open Watcom Contributors. All Rights Reserved.

The batch file to compile app:

```Batchfile
set WATCOM=c:\watcom
set PATH=%WATCOM%\BINNT64;%WATCOM%\BINNT;%PATH%
set INCLUDE=%WATCOM%\H;%WATCOM%\H\NT
wcc386 t.c  -fo=t.obj
wrc    t.rc -r -fo=t1.res -zm
wrc    t.rc -r -fo=t2.res
wlink SYS nt NAME t1.exe FILE t.obj OPT res=t1.res
wlink SYS nt NAME t2.exe FILE t.obj OPT res=t2.res
:: bug
t1.exe
:: ok
t2.exe

```
File _t.c_
```c
#include <stdio.h>
int main(void)
{
  printf("hello\n");
  return 0;
}
```

Resource file _t.rc_
```
#define CREATEPROCESS_MANIFEST_RESOURCE_ID  1
#define RT_MANIFEST  24

CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST
BEGIN
  "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>"
  "<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">"
    "<assemblyIdentity name=""" "Testing" """ version=""" "1.2.3" ".0"" type=""win32""/>"
    "<dependency>"
      "<dependentAssembly>"
        "<assemblyIdentity name=""Microsoft.Windows.Common-Controls"" version=""6.0.0.0"" type=""win32"" processorArchitecture=""*"" publicKeyToken=""6595b64144ccf1df""/>"
      "</dependentAssembly>"
    "</dependency>"
    "<compatibility xmlns=""urn:schemas-microsoft-com:compatibility.v1"">"
      "<application>"
        "<supportedOS Id=""{e2011457-1546-43c5-a5fe-008deee3d3f0}""/>"
        "<supportedOS Id=""{35138b9a-5d96-4fbd-8e2d-a2440225f93a}""/>"
        "<supportedOS Id=""{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}""/>"
        "<supportedOS Id=""{1f676c76-80e1-4239-95bb-83d0f6d0da78}""/>"
        "<supportedOS Id=""{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}""/>"
      "</application>"
    "</compatibility>"
  "</assembly>"
END

```

Files provided by  'vszakats' and discussed on https://github.com/vszakats/harbour-core/issues/313
[watcom_wrc_zm_option_bug_demo.zip](https://github.com/open-watcom/open-watcom-v2/files/1317940/watcom_wrc_zm_option_bug_demo.zip)

**Comment by vszakats** [comment] 2017-09-20 22:58
Whitespaces may be relevant in `t.rc` so it'd be nice to put this (and similar pasted texts) inside code fences: https://help.github.com/articles/creating-and-highlighting-code-blocks/

The `.zip` has everything correct.

**Comment by jmalak** [comment] 2017-09-22 06:24
Thanks for your bug report and sample code.
I will fix it ASAP.

**Comment by omm** [comment] 2017-09-22 06:29
Thank you.

**Comment by jmalak** [comment] 2017-09-23 08:46
I thing you should use following approach for Manifest file as we use with Open Watcom.
You should create standard XML file for Manifest file and create following simple resource file.

Resource file t.rc
```
#define CREATEPROCESS_MANIFEST_RESOURCE_ID  1
#define RT_MANIFEST  24

CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST "manifest.xml"

```
It include XML file content into Manifest resource without any processing.

**Comment by vszakats** [comment] 2017-09-23 08:49
This approach requires variables like version number to be manually updated every time, that's the reason I prefer embedding its full text.

**Comment by jmalak** [comment] 2017-09-23 11:10
It is only idea which also fix problem with character set etc.
Yes it suppose some script processing to create XML with valid data.

Anyway problem is with linker resource processing for PE executable format.

**Comment by vszakats** [comment] 2017-09-23 11:24
FWIW the method used here is compiled/linked without problem with MinGW and MSVC, and there should be nothing spec breaking or invalid, though I'm interested to hear if I'm wrong here.

As for character sets, you're right, though with Manifests, it's usually less of an issue, because the app name aside, 7-bit ASCII text is enough. In this particular case the name is also 7-bit ASCII. (AFAIR the charset requirement for the XML are different from the rest of the resource, maybe UTF-8, though it was a while ago I dealt with this.)

Generating Manifest on-the-fly complicates the build process to a great deal, needs a custom solution and unwanted dependencies. The preprocessor is there already, so tapping can cut these issues nicely.

**Comment by jmalak** [comment] 2017-09-23 11:55
Your rc source is OK, there is no problem.
I am now working on linker fix.

**Comment by vszakats** [comment] 2017-09-23 12:18
@jmalak: Thank you so much!

**Comment by jmalak** [comment] 2017-09-24 10:51
it is now fixed.
Problems were in resource compiler and also in the linker for MS resource format.
OW use Watcom resource format internaly and for MS format (-zm option) convert it to MS format.
We have no trouble because OW use Watcom resource format for all OW project.
If you don't need compatibility of .res files with MS format then use wrc -zm option.

Please, check [latest build version of wrc and wlink](https://github.com/open-watcom/travis-ci-ow-builds).

**Comment by vszakats** [comment] 2017-09-24 12:19
@jamalk: Thank you for the fix. I can confirm that the latest build `2.0 beta Sep 24 2017 11:00:56 (32-bit)` does indeed fix the sample (both with and without `-zm`) and our real-life build as well (which no longer uses `-zm`.)

**Comment by jmalak** [comment] 2017-09-24 12:57
Thanks for checking.

**Closed by jmalak** 2017-09-24 12:57 UTC
Labels: bug
