### ISSUE TITLE
string.h and strcasecmp: W131 warning with existing code

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#788] opened 2021-12-27 11:44 UTC
As of, I think, this commit https://github.com/open-watcom/open-watcom-v2/commit/c5c6daa3284f676213da4347ea44535aa960084d, strcasecmp and strncasecmp
are not prototyped in string.h, but only in strings.h. This results in W131
warnings in existing code which used to not. Is this really intended?

**Comment by jmalak** [comment] 2021-12-27 14:43
Yes, it is intended for better compatibility with latest POSIX standard.
POSIX define strcasecmp and strncasecmp functions in <strings.h>.
I read that only some old BSD version has it in <string.h> where it was before in OW, but we prefer POSIX location.

**Comment by sezero** [comment] 2021-12-27 14:49
No turning back about this? If not, please close the ticket.

**Comment by jmalak** [comment] 2021-12-27 15:41
I understand, it is problem for compatibility with other systems which support BSD header version.
we could include conditionally <strings.h> into <string.h> and use some header setup macros for BSD version.
But we need to introduce some new BSD macro. if BSD version will not be active then same problem appears.

**Comment by sezero** [comment] 2021-12-27 16:06
> I understand, it is problem for compatibility with other systems which support BSD header version.

Also a problem with compatibility with older ow versions.  It's not end of the world, though.

**Comment by jmalak** [comment] 2021-12-29 18:22
I am trying to be compatible with POSIX headers.
This problem is caused by BSD exception from BSD 4.4 version.
I don't want to introduce this BSD exception to our headers if it is not necessary. Up-to-date BSD version use proper location.
I don't want ++support BSD specific in header files anyway.
From my point of view (POSIX) previous OW string.h header file is buggy that we need not handle backward compatibility for it. 
For POSIX source it is bug to relate for <string.h> instead of <strings.h>, that it should be fixed in source code.

**Comment by sezero** [comment] 2021-12-29 18:56
stricmp is neither posix, nor ansi, but it is in string.h, sigh..

Anyways, I won't pursue this further. Feel free to close.

**Comment by jmalak** [comment] 2021-12-29 19:25
it's a terror rage how many rule combination is possible in header files

**Closed by jmalak** 2021-12-29 19:25 UTC
