### ISSUE TITLE
DOS 16bit .COM programs have 256 zero byte prepended

### ISSUE THREAD

**Issue by groessler** [open-watcom/open-watcom-v2#158] opened 2015-04-16 14:01 UTC
Hi again,

.COM files start with 256 zero bytes. This happens both with Linux and Win32 'wcl':

$ wcl -zq -bcl=com -fe=hello.com hello.c
$ hexdump -C hello.com | head -4
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000100  eb 6b 4f 70 65 6e 20 57  61 74 63 6f 6d 20 43 2f  |.kOpen Watcom C/|
00000110  43 2b 2b 31 36 20 52 75  6e 2d 54 69 6d 65 20 73  |C++16 Run-Time s|
$ 

Are my parameters correct (-bcl=com)?

**Comment by ArmstrongJ** [comment] 2015-04-16 14:12
Perhaps I'm mistaken, but isn't this expected/allowed based on the file format?  I was under the impression that the initial 256 bytes of a .COM file is ignored:

http://en.wikipedia.org/wiki/COM_file#MS-DOS_binary_format

I glanced at a DOS .COM file I had lying around that was compiled by Borland, and it appears to have contents in the first 256 bytes, but some of it appears to be nonsense (like mentioning it was compiled by Borland).

Please correct me if I'm wrong, though.  I'm not an expert on things like this.

**Comment by groessler** [comment] 2015-04-16 14:23
The first 256 bytes of a .COM program aren't ignored. The .COM program file is loaded at <seg>:0100. CS,DS, ES, and SS are all set to <seg>.
The first 256 bytes are initialized by DOS and contain for example the command line arguments.

The first two or three bytes of your Borland .COM program probably contain a JMP over the "nonsense bytes".

**Comment by groessler** [comment] 2015-04-16 14:28
Ahh, yes, and entry point into the program is seg:0100.

**Comment by ArmstrongJ** [comment] 2015-04-16 14:44
Well then I do not know why it's padded with 0x100 zeros.  Anyone else?

**Comment by jmalak** [comment] 2015-04-16 15:25
The main module must use ORG 100h
Next problem is option -bcl=com which is wrong, you should replace it by
-bt=dos -l=com

**Comment by groessler** [comment] 2015-04-16 15:56
-bt=dos -l=com doesn't help, either
Still zero bytes at the beginning...

**Comment by groessler** [comment] 2015-04-16 16:16
It seems that the problem was introduced in version 349c20b86783c of bld/wl/c/loaddos.c.
If I revert that file to the previous version (575c934fd9e0f1f3) the zero bytes aren't generated.

**Comment by jmalak** [comment] 2015-04-16 17:34
OK. It looks like regression.
Please could you send me your sample to fix it on current version.

**Comment by groessler** [comment] 2015-04-16 17:42
What sample? Just take any old "hello world" C program.

My command line is

$ wcl -zq -bt=dos -l=com -fe=hello.com hello.c

**Comment by groessler** [comment] 2015-04-16 17:43
or

$ wcl -zq -bcl=com -fe=hello.com hello.c

**Comment by jmalak** [comment] 2015-04-16 18:44
Only note to -bcl=com option, it is danger to use it because it define target macro __COM__ not target macro __DOS__ for compiler as it should be for header files.

**Comment by groessler** [comment] 2015-04-16 19:09
You're right. Smells like a bug to me. Or don't I understand the meaning of '-bcl'?

**Comment by jmalak** [comment] 2015-04-16 19:23
COM is only different format for DOS executable, therefore only linker format shoud be changed.
Generaly -bcl=dos is correct because linker know format for dos as exe format.
OWCC utility know target COM, it translate it to DOS for compiler and pass COM to linker, but wcl doesn't have this translation, that if you need to link some non-defaul format you must use -bt=... for specify compiler targer and -l=.. for specify linker output format.
By example if you want Intel HEX output format you use -bt=dos -l=rawhex etc.

**Comment by jmalak** [comment] 2015-04-18 05:49
Thanks for bug report. 
Now it is fixed by https://github.com/open-watcom/open-watcom-v2/commit/15c60bd8a8fd90303634549d9783bb838fc5b5c6

**Closed** 2015-04-18 05:49 UTC
