### ISSUE TITLE
setting up HTML Help in wine

### ISSUE THREAD

**Issue by revelator** [open-watcom/open-watcom-v2#459] opened 2018-06-04 09:51 UTC
Started building on a debian distro zorin os, but im having a big problem with wine in general, because wine must not be used as superuser. Unfortunatly the build scripts require building with sudo which messes up wine permissions. I got around it temporarily by resetting permissions after use but found out 
that the build script cannot see the help compiler at all so i had to copy it out of wine and run it locally instead of via a wine prefix. The dos and windows help files build now but bwipfc croaks on os2 with a conversion error, so what am i missing ?.

**Comment by jmalak** [comment] 2018-06-04 11:12
First, build system is not supported on wine.
May be it works, but untested.
Anyway build system doesn't require to run under superuser, it can be run under standard user.
But take into account, that you need to change owner of all files (git and build binaries) to be same as user profile used for building/git repository.

Standard is to build it without wine under linux/unix and use OW under wine if you need GUI.
The problem is only with Microsoft Windows Help Compilers (32-bit) if you want build Windows Help format or Html format. But Windows HTML help compiler is replaceable by Pascal version of Windows HTML help compiler tools which is running natively on linux and other platforms.

Be careful b... tools are native tools build (for Linux) for building process.
You should use tools from OW build directories which are for appropriate host system.

If you use wipfc compiler outside OW build system then you need to setup "WIPFC" environment variable to point to OW "wipfc" subdirectory which hold NLS (National Language Support) definition files.
Anyway I didn't test WIPFC output format regulary, because there is no interest from OS/2 comunity and I have no OS/2 test box. Time-to-time I install ipfc viewer and check it, but it has low priority for me.
Could you describe your testing environment for ipfc file and wipfc compiler.
Is it only problem with ipfc compiler or with ipfc files?
Please could you put here full message or log fragment to demonstrate problem.

**Comment by jmalak** [comment] 2018-06-04 11:53
OW build system use shell scripts for clasic shell, now Bash shell (bsh), that best is to configure appropriate shell for user used for OW build. If you run it under standard user then you don't need sudo.
It is enough to start X terminal or some character console terminal under your profile.

**Comment by jmalak** [comment] 2018-06-04 12:05
I looked into documentation build and there is some wine support for Misrosoft Windows help compilers and also for Pascal version of WIndows HTML Help compiler (read comment in setvars.sh file)
It can be used on Linux but require proper installation of Windows HTML help Compilers or Pascal version.
Looks into docs/mif/onebook.mif makefile for definition.
I didn't test it for long time, that some correction could be necessary.
Try to switch on this feature by appropriate environment variable and by proper configuration of these tools. 
If something unclear ask for it here.

**Comment by ArmstrongJ** [comment] 2018-06-04 12:10
Setting up Microsoft's HTML Help Workshop (and the help compiler) under WINE is not as simple as installing it.  Specifically, a few WINE DLLs need to be replaced with actual Microsoft DLLs.  There's instructions [here](https://help.k15t.com/scroll-chm-exporter/installing-microsoft-html-workshop-under-wine-93290645.html).  In my experience, though, HTML Help Workshop and the compiler still occasionally have trouble under WINE, and it should probably be avoided.

**Comment by revelator** [comment] 2018-06-05 08:59
followed the guide for installing html help workshop and it works fine in wine but im having problems accessing the tools from bash. chmcmd is also installed but the build process still asks for both hhc.exe and hcrtf.exe unless i entirely turn of document generation,even if i export the pascal chmcmd utility.
I did have a hunch that i might need to change the user/group of the build directory so i tried that also but im still getting permission denied unless i build with sudo :/

**Comment by revelator** [comment] 2018-06-05 09:56
p.s not using wipfc from os2 toolset but the one that comes with open watcom /ow/build/binbuild/bwipfc, the error below.
bwipfc -q -inf c_readme.ipf
<c_readme.ipf:0:0> Fatal Error 07: Text conversion error

not sure what causes this maybe a terminal problem like the one that causes the installer to fail on linux ?

**Comment by jmalak** [comment] 2018-06-06 14:22
I use some VirtualBox image of Zorin OS to test.
The build system works normaly under any current user without need to use sudo.
I did following steps:
- create new current user (no administrator)
- create new directory dev in user home and change current directory to point it
- use `"git clone https://github.com/open-watcom/open-watcom-v2.git ow2"` to clone repository to ow2 subdirectory
- create my own shell script `~/dev/ow2.sh` from copy of setvars.sh script by changing `export OWROOT=~/dev/ow2`
- run . ow2.sh to setup build environment, it reports GCC version=5
- `cd ~/dev/ow2`
- run `sh build.sh`

All is build except any documentation because on Ubuntu wgml utility with dosemu or dosbox doesn't work. It is problem of current Ubuntu because I used some older version and it works OK.
Also, Travis CI use older version Ubuntu and it works OK with dosemu.

**Comment by jmalak** [comment] 2018-06-06 14:27
I don't know why but dosbox on Ubuntu is broken.
I can open dosbox window and run DOS commands.
But I can not close it, command exit doesn't work. Only way to close it is kill it.
dosemu report some "smashing stack".

**Comment by jmalak** [comment] 2018-06-06 16:02
If you use bwipfc then problem is that WIPFC environment variable is not set.
It should be something like /ow/wipfc/helper .
Normaly it is setup only temporarilly during documentation build by appropriate make files.

**Comment by jmalak** [comment] 2018-06-06 16:15
problem could be because you create OW directory tree in the filesystem root as root.
you must change access rights to this tree to be accessible by user which will do OW build. But it is standard administration on *NIX systems.

**Comment by jmalak** [comment] 2018-06-06 16:30
to use Free Pascal HTML Help compiler you must 
- undefined OWHHC environment variable
- define OWCHMCMD environment variable 

see notes in setvars.sh

**Comment by jmalak** [comment] 2018-06-06 19:27
Ï did some investigation of dosbox problem.
It is fixed by change line in .dosbox/dosbox-0.74.conf file from
`nosound=false`
to
`nosound=true`

**Comment by revelator** [comment] 2018-06-06 19:32
Fixed the permission problem but the bwipfc command still fails even with WIPFC set, same error also.
Even did a full clean, so i suspect some problem with the 64 bit linux bwipfc.
The dosbox problem is known you need to edit dosbox.conf and set cycles to a static value, its normally set to auto, then it should work. I set mine to cycles =90 because else it would run slower than molasses.
html help works now but not from wineprefix, you need to set the help compiler paths to a local folder like /ow/html/hhc.exe and /ow/html/hcrtf.exe and ofcourse replace the mentioned dll's in the wineprefix/drive_c/windows/system32 then it works, but its a bit of a hack.

**Comment by jmalak** [comment] 2018-06-07 03:55
Now I am able to reproduce problem with bwipfc compiler.
I will try to identify source of problem, probably it is some bug in current C++ compiler, because some compiler features are damaged.

**Comment by revelator** [comment] 2018-06-07 09:10
Ok then seems to be the remaining problem. 
Ill probably write up a tutorial sometimes for building on linux
since it seems to not be the easiest thing to do.

**Comment by jmalak** [comment] 2018-06-07 11:03
I updated Wiki a little bit.
Best if you update Wiki Build page where is information related to OW build.

**Comment by revelator** [comment] 2018-06-07 15:01
P.s i used clang as the bootstrap compiler, but the problem with bwipfc also happens with gcc so might be an api bug. Ill see about updating the wiki, just had major backsurgery performed so i cannot say precisely when.

**Comment by jmalak** [comment] 2018-06-13 05:29
I did investigation of the wipfc problem and it looks like bug in wipfc code.
Problem is that if en-US locale is used (it is default for OW build) then on Ubuntu it is supposed only base 7-bit ASCII set (values 0-127) but author of wipfc expect 8-bit range (values 0-255).
Therefore mbstowc is failing for characters > 127.
This problem exist in reading entity.txt file.
It need deaper analysis and probably rework wipfc code.
For better portability change of entity.txt file format could be best solution (not use MBCS->UNICODE translation).

**Comment by jmalak** [comment] 2018-08-27 07:51
Now WIPFC compiler is fixed that properly handle codepage on any platform.
```
bwipfc -q -inf c_readme.ipf
<c_readme.ipf:0:0> Fatal Error 07: Text conversion error
```
this error should not appear anymore and OS/2 documentation should be build OK on any supported platform

**Comment by ewe2** [comment] 2018-11-04 21:54
**jmalak** let me know if this should be in a different issue, but it's related to this so I'll put it down here: I'm having trouble with the build system stripping off quotes-protected paths for hcrtf.exe when it creates winhc.bat. Instead of

```
"C:/Program Files/Help Workshop/hcrtf.exe" -xn cw.hpj
```
which works unchanged from setvars.sh, it strips the quotes off to
```
C:/Program Files/Help Workshop/hcrtf.exe -xn cw.hpj
```
which fails. Is there a way of protecting that variable in `onebook.mif`?

**Comment by jmalak** [comment] 2018-11-05 05:41
The problem should be fixed by changing command for output this command to batch file to
@%append $(wine_hc_batch) "$(hc_nt)" -xn $*.hpj
but it can cause trouble with path without "spaces", it depends on wine batch processor behaviour

**Comment by jmalak** [comment] 2018-11-05 05:42
another possibility is install help compiler to the path without spaces

**Comment by ewe2** [comment] 2018-11-05 05:56
OK, I was hoping it would that simple, wasn't sure of the syntax of that file. By default, that path is where wine installs OWHHC and OWWIN95HC for a user (although I don't really need OWHHC); I did try other things like symlinking to path bin dirs, but it didn't work. But that fixes my issue by escaping that.

**Comment by jmalak** [comment] 2018-11-05 06:01
Take into account that wine is as emulator.
Behaviour of host system (Linux) and guest system (Wine) is totaly different from command line point of view. Symbolic links works for host system but not necessarily for guest system.

**Comment by jmalak** [comment] 2018-11-05 06:03
Anyway fix for this one line should fix your problem in your environment.

**Closed** 2019-01-03 08:31 UTC
