### ISSUE TITLE
incorrect call to __declspec(aborts) ... __stdcall function

### ISSUE THREAD

**Issue by pts** [open-watcom/open-watcom-v2#1010] opened 2022-12-09 01:21 UTC
The following program should exit with exit code 42, but it exits with some other exit code, because OpenWatcom generates code with *jmp* instead of *call*, and with *jmp* the exit code doesn't propagate correctly.

```c
/* demo.c */
__declspec(aborts) __declspec(dllimport) void __stdcall ExitProcess(unsigned uExitCode);
int main(int argc, char **argv) {
  (void)argc; (void)argv;
  ExitProcess(42);
  return 0;
}
```

```
$ owcc -c -bwin32 -Os -s -W -Wall -Wextra -o demo.obj demo.c
$ wdis demo.obj | grep '^0'
0000                            main_:
0000  68 0C 00 00 00                    push            0x0000000c
0005  E8 00 00 00 00                    call            __CHK
000A  51                                push            ecx
000B  6A 2A                             push            0x0000002a
000D  FF 25 00 00 00 00                 jmp             dword ptr __imp__ExitProcess@4
```

In the last line, *jmp* is incorrect, it should be *call* instead. A workaround to get *call* is omitting `__declspec(aborts)` from the declaration of *ExitProcess*. However, this workaround prevents code removal optimizations in the callee.

Explanation why *jmp* is wrong: with the *__stdcall* calling convention the callee expects the argument in `dword ptr [esp+4]` (because `dword ptr [esp]`is the return address). This works fine if the caller uses *push* + *call*. However, if the caller uses *push* + *jmp*, then the argument ends up in `dword ptr [esp]`, but the callee stil uses some garbage value at `dword ptr [esp+4]`.

**Comment by jmalak** [comment] 2022-12-09 13:36
Thanks for your bug report.
It looks like bug in code generator for "abort" modifier processing that it doesn't correctly handle jmp stack frame for various calling conventions.

**Comment by jmalak** [comment] 2022-12-12 00:49
It is fixed now in git repository and it will be available after re-building OW distribution
I also enabled to use __declspec(noreturn) in WIN32 API header files that you don't need to define
__declspec(aborts) __declspec(dllimport) void __stdcall ExitProcess(unsigned uExitCode);
in your code, now it is defined in WIN32 header files

**Comment by jmalak** [comment] 2022-12-18 15:28
It should be fixed by 12a52272fee09a8a47b6d1f91508d833c93e0f18 submit
Anyway __declspec(aborts) is not portable, you shouldn't use it for external code
construct __declspec(noreturn) is portable and is suitable for WIN32 API , but now appropriate OW WIN32 API contains __declspec(noreturn) that it is not necessary to add it in your code

**Closed** 2022-12-19 09:49 UTC
Labels: bug, CG

**Comment by pts** [comment] 2023-06-22 09:05
Please note that this bug is still present with `__declspec(aborts) void __cdecl my_exit(int xc) { exit(xc); }`: `jmp` is generated with only *xc* (and not the return address) pushed, and *my_exit* tries to find the *xc* argument at the wrong stack address.

The bug is not present with `__declspec(noreturn)`.

**Comment by jmalak** [comment] 2023-06-22 17:09
It is not a bug. 
__declspec(aborts) is OW optimized form for OW compiled code only and is backward compatible with old OW code. 
Only __declspec(noreturn) is C standard form and fully portable.
