### ISSUE TITLE
Bootstrap failure related to pathgrp2.h using OW1.9 on Linux

### ISSUE THREAD

**Issue by ArmstrongJ** [open-watcom/open-watcom-v2#590] opened 2020-03-14 20:23 UTC
I just noticed that my nightly builds are failing:

```
**** Building the wasaxp bootstrap
==== 03:01:13 /home/buildbot/slave-local1/global_build_rel/git/bld/as/axp =====
= 03:01:13 /home/buildbot/slave-local1/global_build_rel/git/bld/as/axp/binbuild =
cpp asi_msg.gh
awk asi_msg.gh
cc asexpr.obj
cc asopernd.obj
cc asmem.obj
Include path differs with PCH file
cc asutils.obj
Include path differs with PCH file
cc asregs.obj
cc assymbol.obj
cc asdrectv.obj
cc asdirop.obj
cc asnumlab.obj
cc ashash.obj
cc asmsg.obj
cc alphafmt.obj
cc alphains.obj
yacc asiytab.c
cc asiytab.obj
re2c asilexyy.c
cc asilexyy.obj
cc asinline.obj
cc asiobj.obj
lib asinline.lib
cpp msg.gh
awk msg.gh
mkdir stand
cc stand/asexpr.obj
cc stand/asopernd.obj
cc stand/asmem.obj
Include path differs with PCH file
cc stand/asutils.obj
Include path differs with PCH file
/home/buildbot/slave-local1/global_build_rel/git/bld/as/c/asutils.c(226): Error! E1011: Symbol 'PATH_MAX' has not been declared
/home/buildbot/slave-local1/global_build_rel/git/bld/as/c/asutils.c(226): Error! E1054: Expression must be constant
Error(E42): Last command making (stand/asutils.obj) returned a bad status
Error(E02): Make execution terminated
<wmake -h -f ../binmake bootstrap=1> => non-zero return: 512
Build failed
program finished with exit code 1
elapsedTime=11.564170
```

It looks like the failure started happening around December 25, 2019.  Based on the message, I'm guessing it is related to bcadb30d2818954889106a743ed1b1a72f140da4.

**Comment by ArmstrongJ** [comment] 2020-03-14 20:27
For reference: [build log](http://buildbot.approximatrix.com/builders/global_build_rel/builds/2199/steps/Global%20Bootstrap%20Build/logs/stdio)

**Comment by jmalak** [comment] 2020-03-14 22:09
I tested it on Windows with OW1.9 and it works.
The problem is that Linux headers in OW 1.9 is not fully compatible with "dos" version used on Windows.
I will check it and fix it.

**Comment by jmalak** [comment] 2020-03-16 10:03
It should be fixed now.
I added to Azure Pipelines builds extra bootstrap build by OW 1.9 tools on Linux and Windows that it will be fixed quickly and not wait for bug report.

**Comment by jmalak** [comment] 2020-03-16 15:46
it is fixed for Windows now

**Closed by jmalak** 2020-03-16 15:46 UTC
Labels: bug

**Comment by ArmstrongJ** [comment] 2020-03-16 23:45
Thanks, @jmalak !  I saw my build this morning worked fine, but you were faster than I was at closing this bug.  Good to hear it'll be checked via pipelines from now on.
