### ISSUE TITLE
Compiler Returns Zero Return Code When Warnings Present

### ISSUE THREAD

**Issue by CyberSimian** [open-watcom/open-watcom-v2#239] opened 2016-02-29 22:14 UTC
This is a regression from the behaviour of OW 1.9.  I used my "wcw.bat" file to compile the following source file:

```
int afunc(long* parm);

short avalue = 999;

int main(int argc, char* argv[])
{
  short* myparm;
  myparm=&avalue;
  afunc(myparm);
  return(0);
}
```

Here is the console log for OW 1.9, showing that the return code is 8 for the above program:

```
E:\projects\watcom\bugs\missing_rc>wcw.bat retcode.c

E:\projects\watcom\bugs\missing_rc>wcc386.exe retcode.c /olr /wx /zc /zm /mf /5
/fp3 /bt=nt /fo=retcode_w /fr=retcode_w /dOPSYS_WIN /i=.;E:\watcom\ow190\h\nt;E:
\watcom\ow190\h;
Open Watcom C32 Optimizing Compiler Version 1.9
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
retcode.c(9): Error! E1071: Type of parameter 1 does not agree with previous def
inition
retcode.c(9): Note! N2003: source conversion type is 'short *'
retcode.c(9): Note! N2004: target conversion type is 'long *'
retcode.c(9): Note! N2002: 'afunc' defined in: retcode.c(1)
retcode.c: 11 lines, included 35, 0 warnings, 1 errors
Return code: 8
```

Here is the console log for OW 2.0 showing that the return code is zero:

```
E:\projects\watcom\bugs\missing_rc>wcw.bat retcode.c

E:\projects\watcom\bugs\missing_rc>wcc386.exe retcode.c /olr /wx /zc /zm /mf /5
/fp3 /bt=nt /fo=retcode_w /fr=retcode_w /dOPSYS_WIN /i=.;E:\watcom\ow200\h\nt;E:
\watcom\ow200\h;
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Apr  2 2015 10:46:15 (32-bit)
Copyright (c) 2002-2015 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
retcode.c(9): Warning! W1176: Parameter 1, pointer type mismatch
retcode.c(9): Note! N2003: source conversion type is 'short *'
retcode.c(9): Note! N2004: target conversion type is 'long *'
retcode.c(9): Note! N2002: 'afunc' defined in: retcode.c(1)
retcode.c: 11 lines, included 36, 1 warnings, 0 errors
Code size: 23
Return code: 0
```

-- from CyberSimian in the UK

**Comment by jmalak** [comment] 2016-03-01 10:01
Thanks for bug report.
It is bug in OW2.0 C compiler.
This issue is classified as Warning by OW2.0 but OW1.9 classify it properly as Error. 
Therefore OW2.0 don't report error by return code.
I will review it and correct compiler classification of this issue as Error and it will fix your problem.

**Comment by jmalak** [comment] 2016-03-01 10:34
It is fixed now in git repository by fa87dff18a9db47e1e0b189cfc4d42e52b7deb75
Bellow is output from fixed compiler.

c:\dev\test>bwcc386 warn.c -wx
Open Watcom C x86 32-bit Optimizing Compiler
Version 2.0 beta Feb 29 2016 20:03:09 (64-bit)
Copyright (c) 2002-2016 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
warn.c(9): Error! E1176: Parameter 1, pointer type mismatch
warn.c(9): Note! N2003: source conversion type is 'short *'
warn.c(9): Note! N2004: target conversion type is 'long *'
warn.c(9): Note! N2002: 'afunc' defined in: warn.c(1)
warn.c: 11 lines, 0 warnings, 1 errors

c:\dev\test>echo %errorlevel%
1

c:\dev\test>

**Comment by CyberSimian** [comment] 2016-03-01 10:43
I had not noticed that OW 1.9 and 2.0 classified the mistake differently (one as "error", the other as "warning");  I had noticed only the change in return code!  Thank you for fixing this.

-- from CyberSimian in the UK

**Comment by jmalak** [comment] 2016-03-01 11:26
It is OK. 
If you have any problem log it here and we identify root cause and fix it if possible.

Anyway in OW2.0 message was changed to be more readable message then old message from OW1.9 compiler which is little bit confusing.

**Closed** 2016-03-02 06:57 UTC
Labels: bug
