### ISSUE TITLE
The status of WGML elimination/reimplementation

### ISSUE THREAD

**Issue by XVilka** [open-watcom/open-watcom-v2#251] opened 2016-05-16 21:32 UTC
I think I remember that on the old wiki of http://www.openwatcom.org/ there was a page about reimplementing WGML and there was some progress on it. Running dosemu just for the sake of generating documentation feels wrong. The question is - do you have that somewhere? Or may be know someone who saved it?

**Comment by jmalak** [comment] 2016-05-17 08:07
It is still work-in-progress on official OW site. It is actively developed, but it is not working on all OW platforms. It will required some work to adopt it by OW V2.0. I stop any update to OW V2.0 for this until it will be in stable status. We have up-to-date copy of official Perforce repository in git [OW 1.9 Perforce repository](https://github.com/open-watcom/owp4v1copy)

**Comment by jschwartzenberg** [comment] 2016-05-22 15:32
Maybe it would be possible to have an argument for the build script which disables the parts which depend on WGML?

**Comment by jmalak** [comment] 2016-05-22 16:29
Build of GUI/UI tools depend on header file created by wgml utility (it is used for context help links). It is reason why it is not possible for full OW build even if it is without documentation.

**Comment by jschwartzenberg** [comment] 2016-05-22 16:32
But then the compilers can still be built. These are the most important. (Automated) builds which rely on Open Watcom will work with that.

**Comment by jmalak** [comment] 2016-05-22 16:59
If you want to create sub-set of OW tools then you can do it localy. Because what should be in this sub-set is personaly dependent. Now OW tree hold only what is designed for full OW build. If we get some consensus here about this sub-set then it is possible to include it into OW git repository. But compile only compilers is useless, bacause you need full toolchain.

**Comment by jschwartzenberg** [comment] 2016-05-22 17:02
Sorry, I meant that the whole command-line tool suite could be built. Compilers, linkers, etc.

**Comment by jmalak** [comment] 2016-05-22 17:10
Yes, but you need customize bld/builder.ctl.
You can comment out GUI/UI tools items which require WGML utility.

**Comment by joncampbell123** [comment] 2016-05-27 23:42
I have a fork of Open Watcom v2 that has the WGML and DOSEMU parts disabled for this very reason, if you want to use it right away.

https://github.com/joncampbell123/open-watcom-v2

**Comment by jschwartzenberg** [comment] 2016-05-28 23:09
Thanks! Your IFDEFs seem to do the trick nicely. Would it make sense to get this change into the main tree with OWDOCBUILD defined by default?

It would also seem useful to be able to select which platforms get build. I think in general people may only need to build the toolchain for a single host system.

**Comment by joncampbell123** [comment] 2016-05-28 23:27
@jschwartzenberg I would love for that to happen, however past attempts have been unsuccessful despite arguments with other devs in this project.

I would like to reiterate that the reason I added the IFDEFs the way I did is that I care about the compiler. I could care less about the IDE and help system (the parts that require WGML to build). I work on the command line when I write code, and the manuals can be found online as PDFs anyway. Maybe it's just miscommunication with this project but for some reason they don't seem to want my change in the master repository.

**Comment by ArmstrongJ** [comment] 2016-05-29 00:32
I think a change to`setvars.sh` to disable building the GUI would be appropriate.  I'm not sure what changes @joncampbell123 made, but I think most configuration changes should occur in `setvars.sh`.

I also don't think "they," in reference to this project, are particularly against changes.  I believe the idea is that:

1. The default build should be "all," which seems reasonable
2. Changes to one's particular build configuration should be in `setvars.sh`
3. Breaking the current complicated build system is a big no-no

Just argue your point in a pull request or bug.  This fork of Open Watcom is definitely about moving forward.  The project's "developers," comprised almost entirely of one person, seem to be doing a great job considering the resources.

I'd like to see a pull request from @joncampbell123 with a clean change to disable the requirements on WGML.  I don't think anyone would be against that.

**Comment by joncampbell123** [comment] 2016-05-29 07:56
@ArmstrongJ Sounds good. I'll make a branch straight off the current state of the repository and recreate my changes as a pull request.

**Comment by jmalak** [comment] 2016-05-29 11:04
I didn't submit proposed change because it change existing behavior unwanted way.
It is necessary differ between customization of build process and global change of build process.
Please look into Wiki page [Build process control](https://github.com/open-watcom/open-watcom-v2/wiki/Build#build-process-control) for description of how you can control build process and use it as guide how it can be changed and don't break existing control variables functionality. Variable should be self-explanatory, by example it can be OWONLYCMDLTOOLS or something similar. You should be sure what you realy want to do and what has sense for others. I don't think that removing only items dependent on WGML utility has no much value.

**Comment by joncampbell123** [comment] 2016-05-29 20:40
How about OWIDEBUILD=0 to disable building the IDE?

**Comment by ArmstrongJ** [comment] 2016-05-30 00:15
Not bad, but it looks like your code in #256 also disables a GUI setup library and WGML's build script itself (whatever it does).  I would lean still towards `OWGUIBUILD` because of that.  Anyone else have any thoughts?

I'd also suggest disabling WGML's build script if and only if your new variable and `OWDOCBUILD` are both zero, meaning WGML is unnecessary.

**Comment by joncampbell123** [comment] 2016-05-30 03:09
Does the [ IFDEF ] system in builder.ctl allow boolean combinations i.e. to say that the next block applies if THIS and THAT or if THIS or THAT? Or do I have to use [ IFDEF ]...[ IFDEF ] then [ ENDIF ]...[ ENDIF ]?

**Comment by jmalak** [comment] 2016-05-30 05:46
I fully agree with @ArmstrongJ. We should disable some kind of tools which has sense because removing only WGML dependency is useless. It is a few minutes to install DOSBOX and do full build without restriction. I think limiting set of OW tools to build has sense for people which want build OW by example for one platform (UNIX like) and don't want build GUI staff at all (it is mostly for Windows and OS/2).

IFDEF command function can use expression as argument indirectly with limitation.
Take into account that arguments are processed as string with substitution only.
Bellow is copy of related section from builder documentation [Builder](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/builder/builder.doc)

```

        [BLOCK match word1 word2 word3...]

The "match" word is compared in turn with the words following. If it matches
one of the words following, the commands following are executed. If none
of the words match, the commands are skipped, until the next BLOCK directive
or until the end of the control file. In other words, BLOCK directives cannot
be nested. If you want to start unconditional execution of commands after
you've had a sequence of BLOCK's, just use a BLOCK that's sure to match, e.g.:
        [BLOCK . .]
The "match" word can be a single word, or multiple words. If multiple words,
they must be surrounded by parentheses. Within parentheses, a special 'word'
is the empty word formed by two double quotes. For example, (os_linux "")
will match "os_linux" or nothing .


        [IFDEF match word1 word2 word3...]

This works the same as BLOCK, except that an IFDEF can occur inside and
outside a BLOCK. An IFDEF is terminated by another IFDEF (they cannot be
nested), an ENDIF or a BLOCK. An IFDEF may occur inside or outside a BLOCK.


        [ENDIF]

This terminates a preceding IFDEF. It has no effect on the BLOCK.
```
Below is a few examples how can be released some simple expressions. \<name\> is environment variables which is substituted \<1\> ... are calling parameters for builder.
```
# Set default output directory
[ BLOCK .<OWRELROOT> . ]
#=======================
    set OWRELROOT=<OWROOT>\rel
    [ IFDEF <BLD_HOST> UNIX ]
        set OWRELROOT=<OWROOT>/rel
    [ ENDIF ]

[ BLOCK . . ]
#============
```

```
[ BLOCK <1> build rel ]
#======================
    echo We're in block (build rel)
    [ IFDEF os_os2 <2*> ]
        echo os_os2 detected in parms 2+
    [ IFDEF ("") <2*> ]
        echo no extra parms detected
    [ IFDEF (os_os2 os_linux) <2*> ]
        echo linux or os2 detected
    [ IFDEF (os_os2 os_linux "") <2*> ]
        echo linux or os2 or nothing detected
    [ IFDEF (os_nt) <2*> ]
        echo Oh no! Not Windows please

[ BLOCK . .]
```

**Comment by jmalak** [comment] 2016-05-30 07:12
Anyway did you tried something like
**builder build os_dos**

**Comment by joncampbell123** [comment] 2016-05-30 19:57
@ArmstrongJ OWGUIBUILD is good, I'll use that.

**Comment by joncampbell123** [comment] 2016-05-31 03:26
Do you consider the browser (bld/browser) something to control with OWGUIBUILD or OWDOCBUILD?

**Comment by joncampbell123** [comment] 2016-05-31 04:37
Try #2 committed. Builds fine on my end.

**Comment by jmalak** [comment] 2016-05-31 06:01
I am sorry, you still try to import to build system something to suppress only WGML utility dependency.
As I stateted several times it is "not acceptable"! Right solution is to install DOSBOX and use it for building. If you will give me any good reason why it is not possible we can fix it. WGML utility is integral part of OW build now and will be in the future even if it is only DOS utility now and is unclear if native version will be available.

My understandig of OWGUIBUILD variable is to build all tools which use Window based interface (Windows and OS/2 host systems).
It has nothing to do with IDE and Browser only therefore don't rely on this anywhere and rely only to GUI tools to prevent any confusion. 
You should clasify what all is GUI tools/projects to include all to this logic.
By example All utilities from SDK projects are GUI tools, also Windowed Debugger should be suppres etc.

If you want selectively suppress some projects then you should use totaly diferent design using of something as OWNOBUILD=...list of OW projects... . This variable will be useful for users as you which don't want build something for some reason but has no sense for any other users. It will be on user decision what prefere and what not. Unfortunately it will be more complex change which should be implemented in builder control files in "build" subdirectory (defdylib.ctl deflib.ctl defrule.ctl deftool.ctl master.ctl) and also review/change of project names used by builder will be necessary.

**Comment by ArmstrongJ** [comment] 2016-05-31 11:23
@joncampbell123 Pull request #257 should disable _all_ GUI tools, like @jmalak said.  That would include, of course, the windowed debugger (wdw) and other tools that I can't think of.  You can add a commit to the pull request rather than creating a new one that fixes this minor shortcoming.  

You shouldn't need to disable the `bld/wgml` builder, I wouldn't think.  Doesn't that attempt to build the wgml replacement?  I would guess that simply disabling the doc and gui builds would just mean that the DOS wgml that already exists.  Am I incorrect?

@jmalak's idea about selecting tools to build would be interesting, but extremely complicated due to all the interdependency amongst the lower-level tools.

**Comment by jmalak** [comment] 2016-05-31 11:48
**@ArmstrongJ**  the idea is to disable build of exact part, unfortunately it can not solve dependency if somebody use it to suppress build for some part then must understand what is doing and do right selection.

**Comment by jmalak** [comment] 2016-06-02 20:14
I implemented OWNOBUILD environment variable into builder control files that now is possible suppress build of any OW project or list of project. If you fill OWNOBUILD with list of projects then they are skipped during build process.

**Comment by jschwartzenberg** [comment] 2016-06-07 19:29
I can confirm this works. I just did a build with the following line added to my setvars.sh:
export OWNOBUILD="browser ide bdiff wgml"

(browser, ide and wgml, trigger dosemu, bdiff was failing to build for another reason)

Maybe it would be an idea to add an example OWNOBUILD line to the default setvars.sh which makes more sense.

Thanks!

**Comment by jmalak** [comment] 2016-06-08 05:26
Thanks for note. I updated Wiki, but I will add sample lines for OWNOBUILD and OWGUINOBUILD to setvers script because it looks like that it is usefull functionality for developpers.
I finished implementation of OWGUINOBUILD build control variable which suppress build of tools GUI versions and related items. If you use this control variable then Window mode Debugger is not build but Character mode Debugger is, same logic for vi editor etc.

**Comment by jmalak** [comment] 2016-06-08 05:46
I hope that OWNOBUILD and OWGUINOBUILD control variables are able to help with any specific requirements for build system and don't break any standard OW build functionality. Both variables can be combined because theirs processing is completely independend.

**Comment by jmalak** [comment] 2016-06-10 22:02
Now OWGUINOBUILD control variable is added (see Wiki for description) which suppress build of tools GUI versions.

**Comment by ArmstrongJ** [comment] 2016-06-10 22:05
Can we close this bug for now?  I think @jmalak's variable editions effectively fix the original problem as reported.  I realize that WGML hasn't been "reimplemented" as this issue suggests, but the requirement to run it has been loosened.

**Comment by jmalak** [comment] 2016-06-11 06:05
I will close this issue.
If any trouble with new functionality then reopen this issue or add new one.

**Closed by jmalak** 2016-06-11 06:05 UTC
Labels: enhancement
